//! The bootstraps' lifetime view with a tail (decision 9 of
//! `docs/design/reserving-v02.md`): Mack's bootstrap against R ChainLadder's
//! `MackChainLadder(tri, tail = ...)` on RAA, GenIns and ABC
//! (`reference/reserving_tails_r.csv`, generated by
//! `scripts/reserving_tails_r.R`).
//!
//! * A constant tail, its factor drawn per simulation from the lognormal
//!   with the factor as mean and Mack's tail standard error, and the step to
//!   ultimate given Mack's tail sigma as process error: each origin's and
//!   the total standard deviation is R's `Mack.S.E` with the tail within five
//!   Monte Carlo standard errors, `sd * sqrt((kurtosis - 1) / (4 n))`, and
//!   the mean R's reserve within five standard errors of the mean. That is
//!   `tail = 1.05` with the tail's sigma and standard error extrapolated
//!   (either rule for the last sigma) or given (`tail.se`, `tail.sigma`),
//!   and `tail = TRUE` too when the bootstrap's tail is the constant R's
//!   rule fits: R's `tail.se` for `tail = TRUE` is the extrapolation at that
//!   factor, as a constant tail's is. As without a tail
//!   (`reserving_mack_bootstrap.rs`), the resampled residuals have the
//!   pool's variance `v = 1 - m^2`, so the parameter error of the factors
//!   within the triangle is `v` times Mack's; the tail factor's draw has
//!   Mack's variance exactly. The reference variance is therefore
//!   `process^2 + v parameter^2 + (1 - v) (C se)^2`, with `C` the projected
//!   value at the oldest age (the ultimate over the tail factor) and `se`
//!   the tail's standard error, all from R. Parameter error alone
//!   (`MackProcess::None`) is checked the same way without the process.
//! * An estimated tail (`Tail::LogLinear`, R's `tail = TRUE` rule) refitted
//!   on each simulation's pseudo factors: its process error is R's. Run with
//!   the Gamma process and with none on the same seed, the two share every
//!   pseudo factor and refitted tail (the process draws come after them), so
//!   the difference of the two reserves is the process error alone, and its
//!   standard deviation is R's `Mack.ProcessRisk` (with the tail) within five
//!   Monte Carlo standard errors. Its parameter error is the refit's, not R's
//!   extrapolated `tail.se`: on the oldest origin, whose reserve is the tail
//!   step alone, it is the first-order (delta-method) error of the refitted
//!   factor within five standard errors on ABC, and above it on RAA and
//!   GenIns, where the extrapolation is long and the refitted tail convex in
//!   the factors (`knowledge/findings/bootstrap-tail-parameter-error.md`).

use prospicio_reserving::{
    Development, DevelopmentFit, MackBootstrap, MackBootstrapFit, MackProcess, SigmaInterpolation,
    Tail,
};
use prospicio_validation::{Case, reference, triangle};

/// Simulations per run; the tolerances scale with `1 / sqrt` of it.
const SIMS: usize = 20_000;
const SEED: u64 = 20_261_008;
const DATASETS: [&str; 3] = ["raa", "genins", "abc"];

/// Mean, standard deviation and the Monte Carlo standard error of the
/// standard deviation, `sd * sqrt((kurtosis - 1) / (4 n))`.
fn moments(x: &[f64]) -> (f64, f64, f64) {
    let n = x.len() as f64;
    let mean = x.iter().sum::<f64>() / n;
    let m2 = x.iter().map(|v| (v - mean).powi(2)).sum::<f64>() / n;
    let m4 = x.iter().map(|v| (v - mean).powi(4)).sum::<f64>() / n;
    if m2 == 0.0 {
        return (mean, 0.0, 0.0);
    }
    let sd = m2.sqrt();
    (mean, sd, sd * ((m4 / (m2 * m2) - 1.0) / (4.0 * n)).sqrt())
}

/// R's `quantity` of `dataset` under reference `method`; `arg` is the
/// origin, or empty.
fn r(cases: &[Case], dataset: &str, method: &str, quantity: &str, arg: &str) -> f64 {
    let found: Vec<&Case> = cases
        .iter()
        .filter(|c| {
            c.get("dataset") == dataset
                && c.get("method") == method
                && c.get("quantity") == quantity
                && c.get("arg") == arg
        })
        .collect();
    assert_eq!(found.len(), 1, "{dataset} {method} {quantity} {arg}");
    found[0].number("expected").unwrap()
}

/// R's per-origin `quantity` (`origin` non-empty) or its total.
fn r_origin(cases: &[Case], dataset: &str, method: &str, quantity: &str, origin: &str) -> f64 {
    if origin.is_empty() {
        r(cases, dataset, method, &format!("total_{quantity}"), "")
    } else {
        r(cases, dataset, method, quantity, origin)
    }
}

/// The rule for the last sigma of a reference method.
fn rule(method: &str) -> SigmaInterpolation {
    if method.ends_with("sigma_mack") {
        SigmaInterpolation::Mack
    } else {
        SigmaInterpolation::LogLinear
    }
}

/// The bootstrap with this process, rule and tail.
fn bootstrap(process: MackProcess, method: &str, tail: Tail) -> MackBootstrap {
    MackBootstrap {
        n_sims: SIMS,
        seed: SEED,
        process,
        development: Development {
            sigma_interpolation: rule(method),
            ..Default::default()
        },
        tail,
        ..Default::default()
    }
}

/// Each origin's draws of the reserve, labelled by origin, then the
/// total's (labelled `""`).
fn columns(fit: &MackBootstrapFit) -> Vec<(String, Vec<f64>)> {
    let n = fit.reserves.n_components();
    let rows = || fit.reserves.draw_matrix().chunks(n);
    let cl = &fit.mack.chain_ladder;
    let mut out: Vec<(String, Vec<f64>)> = cl
        .origins
        .iter()
        .enumerate()
        .map(|(j, p)| (p.to_string(), rows().map(|r| r[j]).collect()))
        .collect();
    out.push(("".into(), rows().map(|r| r.iter().sum()).collect()));
    out
}

/// The variance of the resampled residuals: the pool's mean square less
/// its squared mean.
fn pool_variance(fit: &MackBootstrapFit) -> f64 {
    let pool: Vec<f64> = fit
        .residuals
        .iter()
        .copied()
        .filter(|r| !r.is_nan())
        .collect();
    let n = pool.len() as f64;
    let m = pool.iter().sum::<f64>() / n;
    pool.iter().map(|r| r * r).sum::<f64>() / n - m * m
}

/// The reference methods with a constant tail and the bootstrap's
/// settings for each: `tail = 1.05` (extrapolated or given sigma and
/// standard error) and `tail = TRUE` as the constant R's rule fits.
fn constant_runs(
    cases: &[Case],
    dataset: &str,
    process: MackProcess,
) -> Vec<(&'static str, MackBootstrap)> {
    [
        "mack_tail_constant",
        "mack_tail_constant_sigma_mack",
        "mack_tail_given",
        "mack_tail_loglinear",
        "mack_tail_loglinear_sigma_mack",
    ]
    .into_iter()
    .map(|method| {
        let factor = r(cases, dataset, method, "tail_factor", "");
        let mut b = bootstrap(process, method, factor.into());
        if method == "mack_tail_given" {
            b.tail_std_err = Some(r(cases, dataset, method, "given_tail_std_err", ""));
            b.tail_sigma = Some(r(cases, dataset, method, "given_tail_sigma", ""));
        }
        (method, b)
    })
    .collect()
}

/// Checks the constant-tail runs of every dataset under `process`; with
/// `None` only the parameter error is compared.
fn check_constant(process: MackProcess) {
    let cases = reference("reserving_tails_r.csv");
    let mut failures = Vec::new();
    for dataset in DATASETS {
        for (method, b) in constant_runs(&cases, dataset, process) {
            let fit = b
                .fit(&triangle(dataset), "values")
                .unwrap_or_else(|e| panic!("{dataset} {method}: {e}"));
            // The tail's sigma and standard error are R's, so the analytic
            // standard errors are R's.
            let tail = &fit.mack.chain_ladder.tail;
            for (got, quantity) in [(tail.std_err, "tail_std_err"), (tail.sigma, "tail_sigma")] {
                let want = r(&cases, dataset, method, quantity, "");
                assert!(
                    (got / want - 1.0).abs() < 1e-8,
                    "{dataset} {method} {quantity}: {got} vs R {want}"
                );
            }
            let v = pool_variance(&fit);
            let factor = tail.factor;
            for (origin, draws) in columns(&fit) {
                let process_risk = r_origin(&cases, dataset, method, "process_risk", &origin);
                let parameter = r_origin(&cases, dataset, method, "parameter_risk", &origin);
                // The projected value at the oldest age, over the developing
                // origins for the total: every origin develops in the tail.
                let at_oldest = r_origin(&cases, dataset, method, "ultimate", &origin) / factor;
                let mut want =
                    v * parameter * parameter + (1.0 - v) * (at_oldest * tail.std_err).powi(2);
                if process != MackProcess::None {
                    want += process_risk * process_risk;
                }
                let want = want.sqrt();
                let reserve = r_origin(&cases, dataset, method, "reserve", &origin);
                let (mean, sd, error) = moments(&draws);
                let label = format!("{dataset} {method} {process:?} {origin}");
                if (sd - want).abs() > 5.0 * error {
                    failures.push(format!(
                        "{label}: sd {sd:.1} vs R {want:.1} ({:+.2} Monte Carlo SE)",
                        (sd - want) / error
                    ));
                }
                let mean_error = sd / (SIMS as f64).sqrt();
                if (mean - reserve).abs() > 5.0 * mean_error {
                    failures.push(format!(
                        "{label}: mean {mean:.1} vs R {reserve:.1} ({:+.2} Monte Carlo SE)",
                        (mean - reserve) / mean_error
                    ));
                }
            }
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}

#[test]
fn constant_tail_reconciles_with_mack() {
    check_constant(MackProcess::Gamma);
}

#[test]
fn constant_tail_parameter_error_is_mack() {
    check_constant(MackProcess::None);
}

#[test]
fn refitted_tail_has_mack_process_error() {
    let cases = reference("reserving_tails_r.csv");
    let mut failures = Vec::new();
    for dataset in DATASETS {
        for method in ["mack_tail_loglinear", "mack_tail_loglinear_sigma_mack"] {
            let run = |process| {
                bootstrap(process, method, Tail::LogLinear)
                    .fit(&triangle(dataset), "values")
                    .unwrap_or_else(|e| panic!("{dataset} {method}: {e}"))
            };
            let (full, parameter) = (run(MackProcess::Gamma), run(MackProcess::None));
            let factor = r(&cases, dataset, method, "tail_factor", "");
            assert!((full.mack.chain_ladder.tail.factor / factor - 1.0).abs() < 1e-12);
            for ((origin, with), (_, without)) in
                columns(&full).into_iter().zip(columns(&parameter))
            {
                let process: Vec<f64> = with.iter().zip(&without).map(|(a, b)| a - b).collect();
                let (mean, sd, error) = moments(&process);
                let want = r_origin(&cases, dataset, method, "process_risk", &origin);
                let label = format!("{dataset} {method} {origin}");
                if (sd - want).abs() > 5.0 * error {
                    failures.push(format!(
                        "{label}: process sd {sd:.1} vs R {want:.1} ({:+.2} Monte Carlo SE)",
                        (sd - want) / error
                    ));
                }
                if mean.abs() > 5.0 * sd / (SIMS as f64).sqrt() {
                    failures.push(format!("{label}: mean process error {mean:.1}"));
                }
            }
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}

#[test]
fn refitted_tail_parameter_error_is_the_refits() {
    // The oldest origin's reserve, parameter error alone, is C (T* - 1),
    // T* the refitted tail. Its first-order standard deviation is C times
    // sqrt(sum (dT/df_k)^2 v se_k^2): the pseudo factors are independent
    // with variance v se_k^2, and the gradient of R's rule is taken by
    // central differences on the observed pattern.
    let cases = reference("reserving_tails_r.csv");
    for dataset in DATASETS {
        let method = "mack_tail_loglinear";
        let fit = bootstrap(MackProcess::None, method, Tail::LogLinear)
            .fit(&triangle(dataset), "values")
            .unwrap();
        let cl = &fit.mack.chain_ladder;
        let dev = &cl.development;
        let v = pool_variance(&fit);
        let refit = |dev: &DevelopmentFit| Tail::LogLinear.fit(dev).unwrap().factor;
        let mut variance = 0.0;
        for k in 0..dev.ldf.len() {
            let h = 1e-6 * dev.ldf[k];
            let (mut up, mut down) = (dev.clone(), dev.clone());
            up.ldf[k] += h;
            down.ldf[k] -= h;
            let gradient = (refit(&up) - refit(&down)) / (2.0 * h);
            variance += gradient * gradient * v * dev.std_err[k].powi(2);
        }
        let first_order = cl.latest[0] * variance.sqrt();
        let (_, sd, error) = moments(&columns(&fit)[0].1);
        let z = (sd - first_order) / error;
        // R's extrapolated tail standard error is of the same order as the
        // refit's first-order one (0.0044 against 0.0051 on RAA).
        let r_se = r(&cases, dataset, method, "tail_std_err", "");
        assert!(
            (variance.sqrt() / r_se).ln().abs() < 0.5f64.ln().abs(),
            "{dataset}: {} vs R {r_se}",
            variance.sqrt()
        );
        if dataset == "abc" {
            assert!(z.abs() < 5.0, "{dataset}: {sd} vs {first_order} ({z:+.2})");
        } else {
            // Convex in the factors: wider than first order.
            assert!(z > 5.0, "{dataset}: {sd} vs {first_order} ({z:+.2})");
        }
    }
}
