"""Regenerate validation/reference/reserving_expected_loss_python.csv.

Uses chainladder-python. Run from the repository root:

    uv run --no-project --with chainladder==0.10.1 python validation/scripts/reserving_expected_loss_python.py

Triangles are read from validation/data/{clrd_wkcomp,genins_premium}.csv,
which hold `paid` and `premium`; the exposure is the premium's latest
diagonal, as chainladder-python's examples pass it. `method` is the method
name followed by its settings, `name=value` separated by `;` (`average` is
the Development average). `arg` is the origin year for per-origin quantities
and empty for totals.
"""

import csv
import math
import warnings

import chainladder as cl
import numpy as np
import pandas as pd

OUT = "validation/reference/reserving_expected_loss_python.csv"
DATASETS = ["clrd_wkcomp", "genins_premium"]
VER = cl.__version__
REL = 1e-9
ZERO_ABS = 1e-6

# (method, settings) pairs; each setting becomes `name=value` in `method`.
APRIORI = [0.5, 0.75]
CASES = (
    [("expected_loss", dict(apriori=a, average="volume")) for a in APRIORI]
    + [("bornhuetter_ferguson", dict(apriori=a, average="volume")) for a in APRIORI]
    + [("bornhuetter_ferguson", dict(apriori=0.75, average="simple"))]
    + [("benktander", dict(apriori=0.75, n_iters=n, average="volume")) for n in [1, 2, 5, 100]]
    + [
        ("cape_cod", dict(trend=t, decay=d, average="volume"))
        for t in [0.0, 0.05]
        for d in [1.0, 0.75]
    ]
    + [("cape_cod", dict(trend=0.05, decay=0.75, average="simple"))]
)


def read_triangle(name):
    df = pd.read_csv(f"validation/data/{name}.csv", comment="#")
    df["origin"] = df["origin"].astype(str)
    df["valuation"] = (df["origin"].astype(int) + df["development"] // 12 - 1).astype(str)
    return cl.Triangle(
        df,
        origin="origin",
        development="valuation",
        columns=["paid", "premium"],
        cumulative=True,
    )


def fmt(x):
    return repr(float(x))


def label(method, settings):
    return ";".join([method] + [f"{k}={v}" for k, v in settings.items()])


def estimator(method, settings):
    kw = {k: v for k, v in settings.items() if k != "average"}
    return {
        "expected_loss": cl.ExpectedLoss,
        "bornhuetter_ferguson": cl.BornhuetterFerguson,
        "benktander": cl.Benktander,
        "cape_cod": cl.CapeCod,
    }[method](**kw)


def main():
    rows = []

    def emit(dataset, method, quantity, arg, value, source):
        value = float(value)
        if math.isnan(value):
            raise ValueError(f"NaN for {dataset} {method} {quantity} {arg}")
        abs_tol = ZERO_ABS if value == 0 else 0
        rows.append([dataset, method, quantity, arg, fmt(value), abs_tol, REL, source])

    for name in DATASETS:
        tri = read_triangle(name)
        paid = tri["paid"]
        exposure = tri["premium"].latest_diagonal
        origins = [str(d.year) for d in paid.origin.to_timestamp()]
        latest = paid.latest_diagonal.values[0, 0, :, 0]

        for method, settings in CASES:
            m = label(method, settings)
            model = estimator(method, settings)
            dev = cl.Development(average=settings["average"])
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                model.fit(dev.fit_transform(paid), sample_weight=exposure)
            args = ", ".join(f"{k}={v!r}" for k, v in settings.items() if k != "average")
            src = (
                f"chainladder-python {VER}: {type(model).__name__}({args}).fit("
                f"Development(average='{settings['average']}').fit_transform(paid), "
                "sample_weight=premium.latest_diagonal)"
            )
            ult = model.ultimate_.values[0, 0, :, 0]
            for i, o in enumerate(origins):
                emit(name, m, "ultimate", o, ult[i], src + ".ultimate_")
                emit(name, m, "reserve", o, ult[i] - latest[i], src + ".ibnr_")
            emit(name, m, "total_ultimate", "", ult.sum(), src + ".ultimate_.sum()")
            emit(name, m, "total_reserve", "", (ult - latest).sum(), src + ".ibnr_.sum()")
            if method == "cape_cod":
                apriori = model.apriori_.values[0, 0, :, 0]
                detrended = model.detrended_apriori_.values[0, 0, :, 0]
                for i, o in enumerate(origins):
                    emit(name, m, "apriori", o, apriori[i], src + ".apriori_")
                    emit(name, m, "detrended_apriori", o, detrended[i], src + ".detrended_apriori_")

    with open(OUT, "w", newline="") as f:
        f.write(
            f"# Generated by validation/scripts/reserving_expected_loss_python.py with chainladder-python {VER}.\n"
        )
        f.write("# Triangles from validation/data/{clrd_wkcomp,genins_premium}.csv: column paid, exposure the\n")
        f.write("# latest diagonal of premium. No tail factor. reserve is ultimate minus the latest paid (ibnr_).\n")
        w = csv.writer(f, lineterminator="\n")
        w.writerow(["dataset", "method", "quantity", "arg", "expected", "abs_tol", "rel_tol", "source"])
        w.writerows(rows)
    print(f"wrote {len(rows)} cases to {OUT}")


if __name__ == "__main__":
    np.seterr(all="ignore")
    main()
