# Regenerate validation/reference/reserving_cdr_r.csv from R ChainLadder's
# one-year view (Merz and Wuthrich 2008): CDR(MackChainLadder(tri), dev = "all").
#
# Run from the repository root:
#
#     Rscript validation/scripts/reserving_cdr_r.R
#
# Triangles are read from validation/data/*.csv, as in reserving_r.R. `arg`
# is the origin year for per-origin quantities, `origin:k` for the standard
# error of origin's claims development result in future calendar year k
# (1-based, R's "CDR(k)S.E."), k for the total of year k, and empty for the
# other totals. R reports one column per development period, so the last
# year (k = number of ages) is past the run-off and always zero.

suppressPackageStartupMessages(library(ChainLadder))

OUT <- "validation/reference/reserving_cdr_r.csv"
DATASETS <- c("raa", "genins", "abc", "mw2008", "mw2014")
VER <- as.character(packageVersion("ChainLadder"))
REL <- 1e-9
ZERO_ABS <- 1e-9

read_triangle <- function(name) {
  d <- read.csv(file.path("validation/data", paste0(name, ".csv")), comment.char = "#")
  origins <- sort(unique(d$origin))
  devs <- sort(unique(d$development))
  tri <- matrix(NA_real_, length(origins), length(devs),
                dimnames = list(origin = origins, dev = devs))
  tri[cbind(match(d$origin, origins), match(d$development, devs))] <- d$value
  as.triangle(tri)
}

rows <- character(0)

emit <- function(dataset, method, quantity, arg, value, source) {
  abs_tol <- if (value == 0) ZERO_ABS else 0
  rows <<- c(rows, sprintf("%s,%s,%s,%s,%s,%s,%s,%s", dataset, method, quantity,
                           arg, sprintf("%.15g", value), format(abs_tol),
                           format(REL), source))
}

# Volume-weighted factors (alpha = 1) and no tail, the only setting the
# Merz-Wuthrich formulas hold for.
METHODS <- list(
  cdr            = "log-linear",
  cdr_sigma_mack = "Mack"
)

for (name in DATASETS) {
  tri <- read_triangle(name)
  n <- ncol(tri)
  origins <- rownames(tri)
  for (method in names(METHODS)) {
    est <- METHODS[[method]]
    m <- MackChainLadder(tri, est.sigma = est)
    cdr <- CDR(m, dev = "all")
    src <- sprintf("R ChainLadder %s: CDR(MackChainLadder(tri, est.sigma='%s'), dev='all')",
                   VER, est)
    for (i in seq_along(origins)) {
      o <- origins[i]
      emit(name, method, "reserve", o, cdr$IBNR[i], paste0(src, "$IBNR"))
      emit(name, method, "one_year_se", o, cdr[i, "CDR(1)S.E."], paste0(src, "$`CDR(1)S.E.`"))
      for (k in seq_len(n)) {
        col <- sprintf("CDR(%d)S.E.", k)
        emit(name, method, "cdr_se", sprintf("%s:%d", o, k), cdr[i, col],
             sprintf("%s$`%s`", src, col))
      }
      emit(name, method, "mack_se", o, cdr[i, "Mack.S.E."], paste0(src, "$Mack.S.E."))
    }
    total <- nrow(cdr)
    emit(name, method, "total_reserve", "", cdr$IBNR[total], paste0(src, "$IBNR Total"))
    emit(name, method, "total_one_year_se", "", cdr[total, "CDR(1)S.E."],
         paste0(src, "$`CDR(1)S.E.` Total"))
    for (k in seq_len(n)) {
      col <- sprintf("CDR(%d)S.E.", k)
      emit(name, method, "total_cdr_se", k, cdr[total, col], sprintf("%s$`%s` Total", src, col))
    }
    emit(name, method, "total_mack_se", "", cdr[total, "Mack.S.E."],
         paste0(src, "$Mack.S.E. Total"))
  }
}

header <- c(
  sprintf("# Generated by validation/scripts/reserving_cdr_r.R with R %s, ChainLadder %s.",
          paste(R.version$major, R.version$minor, sep = "."), VER),
  "# Triangles from validation/data/{raa,genins,abc,mw2008,mw2014}.csv. Volume-weighted factors,",
  "# no tail. Standard errors, not mean squared errors. cdr_se arg is origin:k, k the 1-based",
  "# future calendar year; R's last year (k = number of ages) is past the run-off and zero.",
  "dataset,method,quantity,arg,expected,abs_tol,rel_tol,source"
)
con <- file(OUT, "wb")
writeLines(c(header, rows), con)
close(con)
cat(sprintf("wrote %d cases to %s\n", length(rows), OUT))
