# Regenerate validation/reference/reserving_glm_r.csv: the over-dispersed
# Poisson reserving model as R's quasi-Poisson GLM,
#
#     glm(inc ~ factor(origin) + factor(dev), family = quasipoisson)
#
# fitted to the observed incremental cells.
#
# Run from the repository root:
#
#     Rscript validation/scripts/reserving_glm_r.R
#
# Triangles are read from validation/data/*.csv. RAA is left out: it has a
# negative increment (1982 at 84 months), which R's quasipoisson family
# rejects ("negative values not allowed"), as does prospicio-glm's Poisson family.
#
# Quantities: `coefficient` and `std_error` (arg is the prospicio-models column
# name, e.g. "origin[2002]" for R's "factor(origin)2002"), `dispersion`
# (Pearson, as summary.glm reports it), `reserve` (arg is the origin year;
# the sum of predicted future cells) and `total_reserve`.

OUT <- "validation/reference/reserving_glm_r.csv"
DATASETS <- c("genins", "abc")
REL <- 1e-9

rows <- character(0)
emit <- function(dataset, quantity, arg, value, source) {
  rows <<- c(rows, sprintf("%s,odp_glm,%s,%s,%s,0,%s,%s", dataset, quantity, arg,
                           sprintf("%.17g", value), format(REL), source))
}

rename <- function(name) {
  name <- sub("^factor\\(origin\\)(.*)$", "origin[\\1]", name)
  sub("^factor\\(dev\\)(.*)$", "development[\\1]", name)
}

for (name in DATASETS) {
  d <- read.csv(file.path("validation/data", paste0(name, ".csv")), comment.char = "#")
  d <- d[order(d$origin, d$development), ]
  d$inc <- ave(d$value, d$origin, FUN = function(v) c(v[1], diff(v)))
  d$dev <- d$development
  origins <- sort(unique(d$origin))
  devs <- sort(unique(d$dev))

  fit <- glm(inc ~ factor(origin) + factor(dev), family = quasipoisson, data = d,
             control = glm.control(epsilon = 1e-14, maxit = 100))
  s <- summary(fit)
  src <- sprintf("R %s glm(inc ~ factor(origin) + factor(dev), family = quasipoisson)",
                 getRversion())

  co <- s$coefficients
  for (i in seq_len(nrow(co))) {
    emit(name, "coefficient", rename(rownames(co)[i]), co[i, "Estimate"], src)
    emit(name, "std_error", rename(rownames(co)[i]), co[i, "Std. Error"], src)
  }
  emit(name, "dispersion", "", s$dispersion, paste0(src, " summary()$dispersion"))

  # Future cells: below the latest diagonal of a square triangle.
  grid <- expand.grid(origin = origins, dev = devs)
  observed <- paste(d$origin, d$dev)
  future <- grid[!(paste(grid$origin, grid$dev) %in% observed), ]
  future$mean <- predict(fit, newdata = future, type = "response")
  for (o in origins) {
    emit(name, "reserve", o, sum(future$mean[future$origin == o]),
         paste0(src, " predict(type = 'response') summed by origin"))
  }
  emit(name, "total_reserve", "", sum(future$mean),
       paste0(src, " predict(type = 'response') summed"))
}

header <- c(
  sprintf("# Generated by validation/scripts/reserving_glm_r.R with R %s (stats::glm).",
          getRversion()),
  "# Triangles from validation/data/{genins,abc}.csv; RAA is left out (negative increment).",
  "dataset,method,quantity,arg,expected,abs_tol,rel_tol,source"
)
writeLines(c(header, rows), OUT)
cat(sprintf("wrote %d cases to %s\n", length(rows), OUT))
