"""Regenerate validation/reference/reserving_clark_python.csv.

Uses chainladder-python's ClarkLDF. Run from the repository root:

    uv run --no-project --with chainladder==0.10.1 python validation/scripts/reserving_clark_python.py

Triangles are read from validation/data/{genins,raa,genins_premium}.csv,
ages in months. Only what chainladder-python defines as R ChainLadder and
act_reserving do is recorded (knowledge/references/chainladder-python-clark.md):

* LDF method (`ClarkLDF().fit(paid)`, genins and raa): `omega_`, `theta_`,
  `scale_`, the link ratios `ldf_` (`arg` is the age in months they develop
  from) and the ultimates of `Chainladder().fit(ClarkLDF().fit_transform(paid))`.
  Its patterns stop at the last age (120 months), so `method` says
  `max_age=120`.
* Cape Cod (`ClarkLDF().fit(paid, sample_weight=premium.latest_diagonal)`,
  genins_premium): `omega_`, `theta_` and `elr_`. Its `scale_` divides by
  incremental fits taken from the latest diagonal, not from the Cape Cod
  expected ultimates, so it is not recorded.

scipy's L-BFGS-B with default tolerances stops about 1e-4 short of the
maximum of the likelihood; every row carries rel_tol 1e-3.
"""

import csv
import warnings

import chainladder as cl
import pandas as pd

OUT = "validation/reference/reserving_clark_python.csv"
VER = cl.__version__
REL = 1e-3
CURVES = ["loglogistic", "weibull"]


def read_triangle(name, columns):
    df = pd.read_csv(f"validation/data/{name}.csv", comment="#")
    df["origin"] = df["origin"].astype(str)
    df["valuation"] = (df["origin"].astype(int) + df["development"] // 12 - 1).astype(str)
    return cl.Triangle(
        df, origin="origin", development="valuation", columns=columns, cumulative=True
    )


def main():
    rows = []

    def emit(dataset, method, quantity, arg, value, source):
        rows.append([dataset, method, quantity, arg, repr(float(value)), 0, REL, source])

    warnings.simplefilter("ignore")
    for name in ["genins", "raa"]:
        paid = read_triangle(name, ["value"])["value"]
        origins = [str(d.year) for d in paid.origin.to_timestamp()]
        ages = [int(a) for a in paid.development]
        for curve in CURVES:
            method = f"clark_ldf;curve={curve};max_age=120"
            src = f"chainladder-python {VER}: ClarkLDF(growth='{curve}').fit(paid)"
            m = cl.ClarkLDF(growth=curve).fit(paid)
            emit(name, method, "omega", "", m.omega_.values[0, 0], src + ".omega_")
            emit(name, method, "theta", "", m.theta_.values[0, 0], src + ".theta_")
            emit(name, method, "sigma2", "", m.scale_.values[0, 0], src + ".scale_")
            ldf = m.ldf_.values[0, 0, 0, :]
            for k, f in enumerate(ldf):
                emit(name, method, "ldf", ages[k], f, src + ".ldf_")
            ult = cl.Chainladder().fit(m.fit_transform(paid)).ultimate_.values[0, 0, :, 0]
            cl_src = (
                f"chainladder-python {VER}: Chainladder().fit("
                f"ClarkLDF(growth='{curve}').fit_transform(paid)).ultimate_"
            )
            for i, o in enumerate(origins):
                emit(name, method, "ultimate", o, ult[i], cl_src)
            emit(name, method, "total_ultimate", "", ult.sum(), cl_src + ".sum()")

    tri = read_triangle("genins_premium", ["paid", "premium"])
    for curve in CURVES:
        method = f"clark_cape_cod;curve={curve};max_age=inf"
        src = (
            f"chainladder-python {VER}: ClarkLDF(growth='{curve}').fit(paid, "
            "sample_weight=premium.latest_diagonal)"
        )
        m = cl.ClarkLDF(growth=curve).fit(tri["paid"], sample_weight=tri["premium"].latest_diagonal)
        emit("genins_premium", method, "omega", "", m.omega_.values[0, 0], src + ".omega_")
        emit("genins_premium", method, "theta", "", m.theta_.values[0, 0], src + ".theta_")
        emit("genins_premium", method, "elr", "", m.elr_.values[0, 0], src + ".elr_")

    with open(OUT, "w", newline="") as f:
        f.write(
            f"# Generated by validation/scripts/reserving_clark_python.py with chainladder-python {VER}.\n"
            "# Ages in months. LDF ultimates are Chainladder on ClarkLDF patterns, which stop at the\n"
            "# last age (max_age=120). Cape Cod scale_ is not comparable and is left out (see script).\n"
        )
        w = csv.writer(f, lineterminator="\n")
        w.writerow(["dataset", "method", "quantity", "arg", "expected", "abs_tol", "rel_tol", "source"])
        w.writerows(rows)
    print(f"wrote {len(rows)} cases to {OUT}")


if __name__ == "__main__":
    main()
