# Regenerate validation/reference/reserving_bootstrap_r.csv from R ChainLadder's
# BootChainLadder (England & Verrall ODP bootstrap).
#
# Run from the repository root:
#
#     Rscript validation/scripts/reserving_bootstrap_r.R
#
# Two kinds of case:
#
# - Deterministic (method odp_bootstrap): the scale phi and the adjusted
#   Pearson residuals, rel_tol 1e-9. `arg` is "<origin year>:<k>" for a
#   residual at 0-based development index k.
# - Stochastic (methods odp_bootstrap_gamma, odp_bootstrap_param): mean and
#   standard deviation of each origin's reserve and of the total, and total
#   quantiles, from N_R simulations. The Rust suite runs N_RUST simulations
#   with a different generator, so each case gets abs_tol = 4 standard errors
#   of the difference: the statistic's standard error at N_RUST, estimated by
#   resampling R's simulations, combined with its standard error at N_R.

suppressPackageStartupMessages(library(ChainLadder))

OUT <- "validation/reference/reserving_bootstrap_r.csv"
DATASETS <- c("raa", "genins", "abc")
VER <- as.character(packageVersion("ChainLadder"))
N_R <- 100000
N_RUST <- 20000   # must match validation/tests/reserving.rs
B <- 200          # resamples per standard error
SEED <- 20261004
QUANTILES <- c(0.75, 0.95, 0.995)

read_triangle <- function(name) {
  d <- read.csv(file.path("validation/data", paste0(name, ".csv")), comment.char = "#")
  origins <- sort(unique(d$origin))
  devs <- sort(unique(d$development))
  tri <- matrix(NA_real_, length(origins), length(devs),
                dimnames = list(origin = origins, dev = devs))
  tri[cbind(match(d$origin, origins), match(d$development, devs))] <- d$value
  as.triangle(tri)
}

rows <- character(0)
emit <- function(dataset, method, quantity, arg, value, abs_tol, rel_tol, source) {
  rows <<- c(rows, sprintf("%s,%s,%s,%s,%s,%s,%s,%s", dataset, method, quantity, arg,
                           sprintf("%.15g", value), sprintf("%.6g", abs_tol),
                           format(rel_tol), source))
}

# Standard error at N_RUST of statistic `stat` over draws `x`, by resampling.
se_at_rust <- function(x, stat) {
  sd(replicate(B, stat(sample(x, N_RUST, replace = TRUE))))
}
stochastic_tol <- function(x, stat) {
  se <- se_at_rust(x, stat)
  4 * sqrt(se^2 + se^2 * N_RUST / N_R)
}

set.seed(SEED)
for (name in DATASETS) {
  tri <- read_triangle(name)
  origins <- rownames(tri)
  n <- ncol(tri)
  boot <- BootChainLadder(tri, R = N_R, process.distr = "gamma", seed = SEED)
  src <- sprintf("R ChainLadder %s: BootChainLadder(tri, R=%d, process.distr='gamma')", VER, N_R)

  resid <- boot$ChainLadder.Residuals[, , 1]
  # R's own nobs: every observed cell, even one whose residual is NaN
  # because its fitted value is zero.
  nobs <- n * (n + 1) / 2
  emit(name, "odp_bootstrap", "scale", "", sum(resid^2, na.rm = TRUE) / nobs, 0, 1e-9,
       paste0(src, " sum(ChainLadder.Residuals^2)/nobs"))
  for (i in seq_len(nrow(resid))) for (k in seq_len(ncol(resid))) {
    r <- resid[i, k]
    if (!is.na(r)) {
      emit(name, "odp_bootstrap", "residual", sprintf("%s:%d", origins[i], k - 1), r,
           1e-9, 1e-9, paste0(src, " ChainLadder.Residuals"))
    }
  }

  sims <- list(
    odp_bootstrap_gamma = boot$IBNR.ByOrigin[, 1, ],
    odp_bootstrap_param = boot$ParamDist.ByOrigin[, 1, ]
  )
  for (method in names(sims)) {
    by_origin <- sims[[method]]
    what <- if (method == "odp_bootstrap_gamma") "IBNR.ByOrigin" else "ParamDist.ByOrigin"
    msrc <- paste0(src, " ", what)
    total <- colSums(by_origin)
    for (i in seq_along(origins)) {
      x <- by_origin[i, ]
      if (all(x == 0)) {
        emit(name, method, "mean_reserve", origins[i], 0, 1e-9, 0, msrc)
        emit(name, method, "sd_reserve", origins[i], 0, 1e-9, 0, msrc)
        next
      }
      emit(name, method, "mean_reserve", origins[i], mean(x), stochastic_tol(x, mean), 0, msrc)
      emit(name, method, "sd_reserve", origins[i], sd(x), stochastic_tol(x, sd), 0, msrc)
    }
    emit(name, method, "mean_total", "", mean(total), stochastic_tol(total, mean), 0, msrc)
    emit(name, method, "sd_total", "", sd(total), stochastic_tol(total, sd), 0, msrc)
    for (p in QUANTILES) {
      q <- function(x) unname(quantile(x, p, type = 1))
      emit(name, method, "quantile_total", format(p), q(total), stochastic_tol(total, q), 0, msrc)
    }
  }
}

header <- c(
  sprintf("# Generated by validation/scripts/reserving_bootstrap_r.R with R %s, ChainLadder %s.",
          paste(R.version$major, R.version$minor, sep = "."), VER),
  sprintf("# Stochastic cases: %d R simulations; abs_tol = 4 standard errors for %d Rust simulations.",
          N_R, N_RUST),
  "dataset,method,quantity,arg,expected,abs_tol,rel_tol,source"
)
writeLines(c(header, rows), OUT)
cat(sprintf("wrote %d cases to %s\n", length(rows), OUT))
