# Low-level bindings to crates/act-r, generated by extendr
# (`wrap__make_actuarialrs_wrappers`, as rextendr does), with the doc blocks
# for these internal environments removed. Internal: use the functions in
# distributions.R, aggregate.R and risk.R.

#' @useDynLib actuarialrs, .registration = TRUE
NULL

compound <- function(frequency, severity, points, method) .Call(wrap__compound, frequency, severity, points, method)

iman_conover_reorder <- function(pd, correlation, seed) .Call(wrap__iman_conover_reorder, pd, correlation, seed)

gpd_mle <- function(exceedances) .Call(wrap__gpd_mle, exceedances)

EventSet <- new.env(parent = emptyenv())

EventSet$simulate <- function(frequency, severity, n_sims, seed) .Call(wrap__EventSet__simulate, frequency, severity, n_sims, seed)

EventSet$n_sims <- function() .Call(wrap__EventSet__n_sims, self)

EventSet$seed <- function() .Call(wrap__EventSet__seed, self)

EventSet$events <- function(sim) .Call(wrap__EventSet__events, self, sim)

EventSet$counts <- function() .Call(wrap__EventSet__counts, self)

EventSet$totals <- function() .Call(wrap__EventSet__totals, self)

#' @export
`$.EventSet` <- function (self, name) { func <- EventSet[[name]]; environment(func) <- environment(); func }

#' @export
`[[.EventSet` <- `$.EventSet`

XolLayer <- new.env(parent = emptyenv())

XolLayer$new <- function(name, limit, attachment, share, aggregate_deductible, aggregate_limit, reinstatements, premium, reinstatement_rates, paid) .Call(wrap__XolLayer__new, name, limit, attachment, share, aggregate_deductible, aggregate_limit, reinstatements, premium, reinstatement_rates, paid)

XolLayer$quota_share <- function(name, cession) .Call(wrap__XolLayer__quota_share, name, cession)

XolLayer$stop_loss <- function(name, limit, retention) .Call(wrap__XolLayer__stop_loss, name, limit, retention)

XolLayer$name <- function() .Call(wrap__XolLayer__name, self)

XolLayer$limit <- function() .Call(wrap__XolLayer__limit, self)

XolLayer$attachment <- function() .Call(wrap__XolLayer__attachment, self)

XolLayer$share <- function() .Call(wrap__XolLayer__share, self)

XolLayer$aggregate_deductible <- function() .Call(wrap__XolLayer__aggregate_deductible, self)

XolLayer$aggregate_limit <- function() .Call(wrap__XolLayer__aggregate_limit, self)

XolLayer$premium <- function() .Call(wrap__XolLayer__premium, self)

XolLayer$reinstatement_rates <- function() .Call(wrap__XolLayer__reinstatement_rates, self)

XolLayer$ceded <- function(losses) .Call(wrap__XolLayer__ceded, self, losses)

XolLayer$ceded_by_event <- function(losses) .Call(wrap__XolLayer__ceded_by_event, self, losses)

XolLayer$reinstatement_premium <- function(losses) .Call(wrap__XolLayer__reinstatement_premium, self, losses)

#' @export
`$.XolLayer` <- function (self, name) { func <- XolLayer[[name]]; environment(func) <- environment(); func }

#' @export
`[[.XolLayer` <- `$.XolLayer`

ReinsuranceTower <- new.env(parent = emptyenv())

ReinsuranceTower$new <- function(layers) .Call(wrap__ReinsuranceTower__new, layers)

ReinsuranceTower$inuring <- function(stages) .Call(wrap__ReinsuranceTower__inuring, stages)

ReinsuranceTower$layer_names <- function() .Call(wrap__ReinsuranceTower__layer_names, self)

ReinsuranceTower$stages <- function() .Call(wrap__ReinsuranceTower__stages, self)

ReinsuranceTower$ceded <- function(losses) .Call(wrap__ReinsuranceTower__ceded, self, losses)

ReinsuranceTower$apply <- function(events) .Call(wrap__ReinsuranceTower__apply, self, events)

#' @export
`$.ReinsuranceTower` <- function (self, name) { func <- ReinsuranceTower[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ReinsuranceTower` <- `$.ReinsuranceTower`

Lognormal <- new.env(parent = emptyenv())

Lognormal$new <- function(meanlog, sdlog) .Call(wrap__Lognormal__new, meanlog, sdlog)

Lognormal$from_mean_cv <- function(mean, cv) .Call(wrap__Lognormal__from_mean_cv, mean, cv)

Lognormal$meanlog <- function() .Call(wrap__Lognormal__meanlog, self)

Lognormal$sdlog <- function() .Call(wrap__Lognormal__sdlog, self)

Lognormal$mean <- function() .Call(wrap__Lognormal__mean, self)

Lognormal$variance <- function() .Call(wrap__Lognormal__variance, self)

Lognormal$cdf <- function(x) .Call(wrap__Lognormal__cdf, self, x)

Lognormal$quantile <- function(p) .Call(wrap__Lognormal__quantile, self, p)

Lognormal$lev <- function(limit) .Call(wrap__Lognormal__lev, self, limit)

Lognormal$stop_loss <- function(retention) .Call(wrap__Lognormal__stop_loss, self, retention)

Lognormal$layer <- function(limit, attachment) .Call(wrap__Lognormal__layer, self, limit, attachment)

Lognormal$sample <- function(n, seed, stream) .Call(wrap__Lognormal__sample, self, n, seed, stream)

#' @export
`$.Lognormal` <- function (self, name) { func <- Lognormal[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Lognormal` <- `$.Lognormal`

Poisson <- new.env(parent = emptyenv())

Poisson$new <- function(lambda) .Call(wrap__Poisson__new, lambda)

Poisson$lambda <- function() .Call(wrap__Poisson__lambda, self)

Poisson$pmf <- function(k) .Call(wrap__Poisson__pmf, self, k)

Poisson$cdf <- function(k) .Call(wrap__Poisson__cdf, self, k)

Poisson$mean <- function() .Call(wrap__Poisson__mean, self)

Poisson$variance <- function() .Call(wrap__Poisson__variance, self)

Poisson$quantile <- function(p) .Call(wrap__Poisson__quantile, self, p)

Poisson$sample <- function(n, seed, stream) .Call(wrap__Poisson__sample, self, n, seed, stream)

#' @export
`$.Poisson` <- function (self, name) { func <- Poisson[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Poisson` <- `$.Poisson`

NegativeBinomial <- new.env(parent = emptyenv())

NegativeBinomial$new <- function(r, beta) .Call(wrap__NegativeBinomial__new, r, beta)

NegativeBinomial$from_mean_variance <- function(mean, variance) .Call(wrap__NegativeBinomial__from_mean_variance, mean, variance)

NegativeBinomial$r <- function() .Call(wrap__NegativeBinomial__r, self)

NegativeBinomial$beta <- function() .Call(wrap__NegativeBinomial__beta, self)

NegativeBinomial$pmf <- function(k) .Call(wrap__NegativeBinomial__pmf, self, k)

NegativeBinomial$cdf <- function(k) .Call(wrap__NegativeBinomial__cdf, self, k)

NegativeBinomial$mean <- function() .Call(wrap__NegativeBinomial__mean, self)

NegativeBinomial$variance <- function() .Call(wrap__NegativeBinomial__variance, self)

NegativeBinomial$quantile <- function(p) .Call(wrap__NegativeBinomial__quantile, self, p)

NegativeBinomial$sample <- function(n, seed, stream) .Call(wrap__NegativeBinomial__sample, self, n, seed, stream)

#' @export
`$.NegativeBinomial` <- function (self, name) { func <- NegativeBinomial[[name]]; environment(func) <- environment(); func }

#' @export
`[[.NegativeBinomial` <- `$.NegativeBinomial`

Grid <- new.env(parent = emptyenv())

Grid$new <- function(step, probs) .Call(wrap__Grid__new, step, probs)

Grid$discretize <- function(severity, step, points, method) .Call(wrap__Grid__discretize, severity, step, points, method)

Grid$step <- function() .Call(wrap__Grid__step, self)

Grid$probs <- function() .Call(wrap__Grid__probs, self)

Grid$report <- function() .Call(wrap__Grid__report, self)

Grid$mean <- function() .Call(wrap__Grid__mean, self)

Grid$variance <- function() .Call(wrap__Grid__variance, self)

Grid$cdf <- function(x) .Call(wrap__Grid__cdf, self, x)

Grid$quantile <- function(p) .Call(wrap__Grid__quantile, self, p)

Grid$lev <- function(limit) .Call(wrap__Grid__lev, self, limit)

Grid$stop_loss <- function(retention) .Call(wrap__Grid__stop_loss, self, retention)

Grid$layer <- function(limit, attachment) .Call(wrap__Grid__layer, self, limit, attachment)

#' @export
`$.Grid` <- function (self, name) { func <- Grid[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Grid` <- `$.Grid`

Sampled <- new.env(parent = emptyenv())

Sampled$new <- function(draws) .Call(wrap__Sampled__new, draws)

Sampled$draws <- function() .Call(wrap__Sampled__draws, self)

Sampled$mean <- function() .Call(wrap__Sampled__mean, self)

Sampled$variance <- function() .Call(wrap__Sampled__variance, self)

Sampled$cdf <- function(x) .Call(wrap__Sampled__cdf, self, x)

Sampled$quantile <- function(p) .Call(wrap__Sampled__quantile, self, p)

Sampled$var <- function(p) .Call(wrap__Sampled__var, self, p)

Sampled$tvar <- function(p) .Call(wrap__Sampled__tvar, self, p)

#' @export
`$.Sampled` <- function (self, name) { func <- Sampled[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Sampled` <- `$.Sampled`

PredictiveDistribution <- new.env(parent = emptyenv())

PredictiveDistribution$new <- function(dims, keys, draws, n_sims) .Call(wrap__PredictiveDistribution__new, dims, keys, draws, n_sims)

PredictiveDistribution$dims <- function() .Call(wrap__PredictiveDistribution__dims, self)

PredictiveDistribution$n_sims <- function() .Call(wrap__PredictiveDistribution__n_sims, self)

PredictiveDistribution$n_components <- function() .Call(wrap__PredictiveDistribution__n_components, self)

PredictiveDistribution$keys <- function() .Call(wrap__PredictiveDistribution__keys, self)

PredictiveDistribution$draw_matrix <- function() .Call(wrap__PredictiveDistribution__draw_matrix, self)

PredictiveDistribution$marginal <- function(key) .Call(wrap__PredictiveDistribution__marginal, self, key)

PredictiveDistribution$aggregate <- function(keep) .Call(wrap__PredictiveDistribution__aggregate, self, keep)

PredictiveDistribution$total <- function() .Call(wrap__PredictiveDistribution__total, self)

PredictiveDistribution$mean <- function() .Call(wrap__PredictiveDistribution__mean, self)

PredictiveDistribution$variance <- function() .Call(wrap__PredictiveDistribution__variance, self)

PredictiveDistribution$quantile <- function(p) .Call(wrap__PredictiveDistribution__quantile, self, p)

PredictiveDistribution$var <- function(p) .Call(wrap__PredictiveDistribution__var, self, p)

PredictiveDistribution$tvar <- function(p) .Call(wrap__PredictiveDistribution__tvar, self, p)

PredictiveDistribution$provenance <- function() .Call(wrap__PredictiveDistribution__provenance, self)

#' @export
`$.PredictiveDistribution` <- function (self, name) { func <- PredictiveDistribution[[name]]; environment(func) <- environment(); func }

#' @export
`[[.PredictiveDistribution` <- `$.PredictiveDistribution`

EvtTail <- new.env(parent = emptyenv())

EvtTail$fit <- function(draws, level) .Call(wrap__EvtTail__fit, draws, level)

EvtTail$threshold <- function() .Call(wrap__EvtTail__threshold, self)

EvtTail$p_exceed <- function() .Call(wrap__EvtTail__p_exceed, self)

EvtTail$xi <- function() .Call(wrap__EvtTail__xi, self)

EvtTail$beta <- function() .Call(wrap__EvtTail__beta, self)

EvtTail$var <- function(p) .Call(wrap__EvtTail__var, self, p)

EvtTail$tvar <- function(p) .Call(wrap__EvtTail__tvar, self, p)

#' @export
`$.EvtTail` <- function (self, name) { func <- EvtTail[[name]]; environment(func) <- environment(); func }

#' @export
`[[.EvtTail` <- `$.EvtTail`

RiskDistortion <- new.env(parent = emptyenv())

RiskDistortion$new <- function(kind, param) .Call(wrap__RiskDistortion__new, kind, param)

RiskDistortion$kind <- function() .Call(wrap__RiskDistortion__kind, self)

RiskDistortion$param <- function() .Call(wrap__RiskDistortion__param, self)

RiskDistortion$g <- function(s) .Call(wrap__RiskDistortion__g, self, s)

RiskDistortion$weights <- function(n) .Call(wrap__RiskDistortion__weights, self, n)

RiskDistortion$measure <- function(x) .Call(wrap__RiskDistortion__measure, self, x)

RiskDistortion$allocate <- function(pd) .Call(wrap__RiskDistortion__allocate, self, pd)

#' @export
`$.RiskDistortion` <- function (self, name) { func <- RiskDistortion[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RiskDistortion` <- `$.RiskDistortion`

RiskCopula <- new.env(parent = emptyenv())

RiskCopula$gaussian <- function(correlation, dim) .Call(wrap__RiskCopula__gaussian, correlation, dim)

RiskCopula$student_t <- function(correlation, dim, nu) .Call(wrap__RiskCopula__student_t, correlation, dim, nu)

RiskCopula$archimedean <- function(family, theta, dim) .Call(wrap__RiskCopula__archimedean, family, theta, dim)

RiskCopula$dim <- function() .Call(wrap__RiskCopula__dim, self)

RiskCopula$description <- function() .Call(wrap__RiskCopula__description, self)

RiskCopula$sample <- function(n, seed) .Call(wrap__RiskCopula__sample, self, n, seed)

RiskCopula$simulate <- function(marginals, n_sims, seed, dims, keys) .Call(wrap__RiskCopula__simulate, self, marginals, n_sims, seed, dims, keys)

#' @export
`$.RiskCopula` <- function (self, name) { func <- RiskCopula[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RiskCopula` <- `$.RiskCopula`
