# Low-level bindings to crates/prospicio-r, generated by extendr
# (`wrap__make_prospicio_wrappers`, as rextendr does), with the doc blocks
# for these internal environments removed. Internal: use the functions in
# distributions.R, aggregate.R, reinsurance.R, reserving.R and risk.R.

#' @useDynLib prospicio, .registration = TRUE
NULL

actual_vs_expected_rust <- function(periods, y, mu, weights, family_name, theta, power, dispersion) .Call(wrap__actual_vs_expected_rust, periods, y, mu, weights, family_name, theta, power, dispersion)

bayes_glm_fit_design <- function(x, names, y, offset, weights, family_name, link_name, theta, power, link_power, prior_sd, intercept_sd, dispersion, dispersion_scale, sampler) .Call(wrap__bayes_glm_fit_design, x, names, y, offset, weights, family_name, link_name, theta, power, link_power, prior_sd, intercept_sd, dispersion, dispersion_scale, sampler)

bayes_stacking_rust <- function(lpd, k, concentration, sampler) .Call(wrap__bayes_stacking_rust, lpd, k, concentration, sampler)

hierarchical_stacking_rust <- function(lpd, k, x, p, priors, pooling, adaptive, discrete, sampler) .Call(wrap__hierarchical_stacking_rust, lpd, k, x, p, priors, pooling, adaptive, discrete, sampler)

blend_by_component_rust <- function(models, weights, seed) .Call(wrap__blend_by_component_rust, models, weights, seed)

dist_to_json_rust <- function(dist) .Call(wrap__dist_to_json_rust, dist)

dist_from_json_rust <- function(text) .Call(wrap__dist_from_json_rust, text)

join_rust <- function(parts, labels, dim, same_simulations) .Call(wrap__join_rust, parts, labels, dim, same_simulations)

reorder_groups_rust <- function(pd, dim, correlation, seed) .Call(wrap__reorder_groups_rust, pd, dim, correlation, seed)

blend_rust <- function(models, weights, seed) .Call(wrap__blend_rust, models, weights, seed)

compound <- function(frequency, severity, points, method) .Call(wrap__compound, frequency, severity, points, method)

stacking_weights_rust <- function(lpd, k) .Call(wrap__stacking_weights_rust, lpd, k)

pseudo_bma_weights_rust <- function(lpd, k, n_draws, seed) .Call(wrap__pseudo_bma_weights_rust, lpd, k, n_draws, seed)

glm_fit_design <- function(x, names, y, offset, weights, family_name, link_name, dispersion_kind, dispersion_value, theta, power, link_power) .Call(wrap__glm_fit_design, x, names, y, offset, weights, family_name, link_name, dispersion_kind, dispersion_value, theta, power, link_power)

elastic_net_fit_design <- function(x, names, y, offset, weights, family_name, link_name, alpha, lambdas, nlambda, min_ratio, standardize, penalty_factor, theta, power, link_power) .Call(wrap__elastic_net_fit_design, x, names, y, offset, weights, family_name, link_name, alpha, lambdas, nlambda, min_ratio, standardize, penalty_factor, theta, power, link_power)

elastic_net_cv_design <- function(x, names, y, offset, weights, family_name, link_name, alpha, lambdas, nlambda, min_ratio, standardize, penalty_factor, theta, power, link_power, foldid) .Call(wrap__elastic_net_cv_design, x, names, y, offset, weights, family_name, link_name, alpha, lambdas, nlambda, min_ratio, standardize, penalty_factor, theta, power, link_power, foldid)

gam_fit_design <- function(x, names, y, offset, weights, family_name, link_name, dispersion_kind, dispersion_value, theta, power, smooths, n_basis, smoothing, lambdas) .Call(wrap__gam_fit_design, x, names, y, offset, weights, family_name, link_name, dispersion_kind, dispersion_value, theta, power, smooths, n_basis, smoothing, lambdas)

family_deviance_rust <- function(family_name, theta, power, y, mu, weights) .Call(wrap__family_deviance_rust, family_name, theta, power, y, mu, weights)

gini_rust <- function(y, pred, exposure) .Call(wrap__gini_rust, y, pred, exposure)

lift_rust <- function(y, pred, exposure, bands) .Call(wrap__lift_rust, y, pred, exposure, bands)

crps_rust <- function(draws, y) .Call(wrap__crps_rust, draws, y)

pinball_rust <- function(y, pred, alpha, weights) .Call(wrap__pinball_rust, y, pred, alpha, weights)

log_score_rust <- function(family_name, theta, power, y, mu, dispersion, weights) .Call(wrap__log_score_rust, family_name, theta, power, y, mu, dispersion, weights)

pit_rust <- function(family_name, theta, power, y, mu, dispersion, weights, seed) .Call(wrap__pit_rust, family_name, theta, power, y, mu, dispersion, weights, seed)

ks_uniform_rust <- function(values) .Call(wrap__ks_uniform_rust, values)

simulate_from_means_rust <- function(family_name, theta, power, means, n_rows, dispersion, weights, n_sims, seed) .Call(wrap__simulate_from_means_rust, family_name, theta, power, means, n_rows, dispersion, weights, n_sims, seed)

k_fold_rust <- function(n, k, seed) .Call(wrap__k_fold_rust, n, k, seed)

group_k_fold_rust <- function(groups, k, seed) .Call(wrap__group_k_fold_rust, groups, k, seed)

time_ordered_rust <- function(periods, n_test) .Call(wrap__time_ordered_rust, periods, n_test)

mcmc_diagnostics_rust <- function(draws, n_chains) .Call(wrap__mcmc_diagnostics_rust, draws, n_chains)

elpd_loo_rust <- function(log_lik, n, r_eff) .Call(wrap__elpd_loo_rust, log_lik, n, r_eff)

elpd_waic_rust <- function(log_lik, n) .Call(wrap__elpd_waic_rust, log_lik, n)

local_pareto_convert <- function(t, alpha, rel_tolerance, stop_survival, stop_at) .Call(wrap__local_pareto_convert, t, alpha, rel_tolerance, stop_survival, stop_at)

claim_count_parameters <- function(mean, dispersion) .Call(wrap__claim_count_parameters, mean, dispersion)

pricing_severity_exposure_curve <- function(severity, mpl, x) .Call(wrap__pricing_severity_exposure_curve, severity, mpl, x)

pricing_price <- function(losses, assets, rate, pricing) .Call(wrap__pricing_price, losses, assets, rate, pricing)

pricing_price_portfolio <- function(pd, assets, rate, pricing) .Call(wrap__pricing_price_portfolio, pd, assets, rate, pricing)

pricing_pentagon <- function(names, values) .Call(wrap__pricing_pentagon, names, values)

pricing_ilf <- function(severity, limit, basic_limit) .Call(wrap__pricing_ilf, severity, limit, basic_limit)

pricing_loss_elimination_ratio <- function(severity, deductible) .Call(wrap__pricing_loss_elimination_ratio, severity, deductible)

pricing_pareto_extrapolation <- function(from, to, alpha, truncation_at) .Call(wrap__pricing_pareto_extrapolation, from, to, alpha, truncation_at)

pricing_alpha_between_layers <- function(a, b, truncation_at) .Call(wrap__pricing_alpha_between_layers, a, b, truncation_at)

pricing_alpha_between_frequency_and_layer <- function(threshold, frequency, limit, attachment, expected_loss, truncation_at) .Call(wrap__pricing_alpha_between_frequency_and_layer, threshold, frequency, limit, attachment, expected_loss, truncation_at)

pricing_alpha_between_frequencies <- function(threshold_1, frequency_1, threshold_2, frequency_2, truncation_at) .Call(wrap__pricing_alpha_between_frequencies, threshold_1, frequency_1, threshold_2, frequency_2, truncation_at)

entropic_rust <- function(draws, theta) .Call(wrap__entropic_rust, draws, theta)

esscher_rust <- function(draws, h) .Call(wrap__esscher_rust, draws, h)

mes_rust <- function(pd, p) .Call(wrap__mes_rust, pd, p)

covar_rust <- function(pd, key, p, q) .Call(wrap__covar_rust, pd, key, p, q)

esscher_allocation_rust <- function(pd, h) .Call(wrap__esscher_allocation_rust, pd, h)

iman_conover_reorder <- function(pd, correlation, seed) .Call(wrap__iman_conover_reorder, pd, correlation, seed)

gpd_mle <- function(exceedances) .Call(wrap__gpd_mle, exceedances)

mean_excess_rust <- function(draws, thresholds) .Call(wrap__mean_excess_rust, draws, thresholds)

hill_rust <- function(draws, ks) .Call(wrap__hill_rust, draws, ks)

EventSet <- new.env(parent = emptyenv())

EventSet$simulate <- function(frequency, severity, n_sims, seed) .Call(wrap__EventSet__simulate, frequency, severity, n_sims, seed)

EventSet$from_years <- function(years, sums_insured, seed, times) .Call(wrap__EventSet__from_years, years, sums_insured, seed, times)

EventSet$with_uniform_times <- function() .Call(wrap__EventSet__with_uniform_times, self)

EventSet$with_seasonal_times <- function(weights) .Call(wrap__EventSet__with_seasonal_times, self, weights)

EventSet$has_times <- function() .Call(wrap__EventSet__has_times, self)

EventSet$times <- function(sim) .Call(wrap__EventSet__times, self, sim)

EventSet$has_sums_insured <- function() .Call(wrap__EventSet__has_sums_insured, self)

EventSet$sums_insured <- function(sim) .Call(wrap__EventSet__sums_insured, self, sim)

EventSet$n_sims <- function() .Call(wrap__EventSet__n_sims, self)

EventSet$seed <- function() .Call(wrap__EventSet__seed, self)

EventSet$events <- function(sim) .Call(wrap__EventSet__events, self, sim)

EventSet$counts <- function() .Call(wrap__EventSet__counts, self)

EventSet$totals <- function() .Call(wrap__EventSet__totals, self)

#' @export
`$.EventSet` <- function (self, name) { func <- EventSet[[name]]; environment(func) <- environment(); func }

#' @export
`[[.EventSet` <- `$.EventSet`

XolLayer <- new.env(parent = emptyenv())

XolLayer$new <- function(name, limit, attachment, share, aggregate_deductible, aggregate_limit, reinstatements, premium, reinstatement_rates, paid, pro_rata_time) .Call(wrap__XolLayer__new, name, limit, attachment, share, aggregate_deductible, aggregate_limit, reinstatements, premium, reinstatement_rates, paid, pro_rata_time)

XolLayer$quota_share <- function(name, cession) .Call(wrap__XolLayer__quota_share, name, cession)

XolLayer$stop_loss <- function(name, limit, retention) .Call(wrap__XolLayer__stop_loss, name, limit, retention)

XolLayer$surplus <- function(name, retention, lines) .Call(wrap__XolLayer__surplus, name, retention, lines)

XolLayer$ceded_with_sums_insured <- function(losses, sums_insured) .Call(wrap__XolLayer__ceded_with_sums_insured, self, losses, sums_insured)

XolLayer$needs_sums_insured <- function() .Call(wrap__XolLayer__needs_sums_insured, self)

XolLayer$name <- function() .Call(wrap__XolLayer__name, self)

XolLayer$limit <- function() .Call(wrap__XolLayer__limit, self)

XolLayer$attachment <- function() .Call(wrap__XolLayer__attachment, self)

XolLayer$share <- function() .Call(wrap__XolLayer__share, self)

XolLayer$aggregate_deductible <- function() .Call(wrap__XolLayer__aggregate_deductible, self)

XolLayer$aggregate_limit <- function() .Call(wrap__XolLayer__aggregate_limit, self)

XolLayer$premium <- function() .Call(wrap__XolLayer__premium, self)

XolLayer$reinstatement_rates <- function() .Call(wrap__XolLayer__reinstatement_rates, self)

XolLayer$ceded <- function(losses) .Call(wrap__XolLayer__ceded, self, losses)

XolLayer$ceded_by_event <- function(losses) .Call(wrap__XolLayer__ceded_by_event, self, losses)

XolLayer$pro_rata_time <- function() .Call(wrap__XolLayer__pro_rata_time, self)

XolLayer$with_loss_corridor <- function(lower, upper, retained) .Call(wrap__XolLayer__with_loss_corridor, self, lower, upper, retained)

XolLayer$loss_corridor <- function() .Call(wrap__XolLayer__loss_corridor, self)

XolLayer$reinstatement_premium <- function(losses, times) .Call(wrap__XolLayer__reinstatement_premium, self, losses, times)

#' @export
`$.XolLayer` <- function (self, name) { func <- XolLayer[[name]]; environment(func) <- environment(); func }

#' @export
`[[.XolLayer` <- `$.XolLayer`

ReinsuranceTower <- new.env(parent = emptyenv())

ReinsuranceTower$new <- function(layers) .Call(wrap__ReinsuranceTower__new, layers)

ReinsuranceTower$inuring <- function(stages) .Call(wrap__ReinsuranceTower__inuring, stages)

ReinsuranceTower$from_json <- function(text) .Call(wrap__ReinsuranceTower__from_json, text)

ReinsuranceTower$to_json <- function() .Call(wrap__ReinsuranceTower__to_json, self)

ReinsuranceTower$layer_names <- function() .Call(wrap__ReinsuranceTower__layer_names, self)

ReinsuranceTower$stages <- function() .Call(wrap__ReinsuranceTower__stages, self)

ReinsuranceTower$ceded <- function(losses) .Call(wrap__ReinsuranceTower__ceded, self, losses)

ReinsuranceTower$on_grid <- function(frequency, severity, points) .Call(wrap__ReinsuranceTower__on_grid, self, frequency, severity, points)

ReinsuranceTower$apply_aggregate <- function(losses) .Call(wrap__ReinsuranceTower__apply_aggregate, self, losses)

ReinsuranceTower$apply <- function(events) .Call(wrap__ReinsuranceTower__apply, self, events)

#' @export
`$.ReinsuranceTower` <- function (self, name) { func <- ReinsuranceTower[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ReinsuranceTower` <- `$.ReinsuranceTower`

Lognormal <- new.env(parent = emptyenv())

Lognormal$new <- function(meanlog, sdlog) .Call(wrap__Lognormal__new, meanlog, sdlog)

Lognormal$from_mean_cv <- function(mean, cv) .Call(wrap__Lognormal__from_mean_cv, mean, cv)

Lognormal$meanlog <- function() .Call(wrap__Lognormal__meanlog, self)

Lognormal$sdlog <- function() .Call(wrap__Lognormal__sdlog, self)

Lognormal$mean <- function() .Call(wrap__Lognormal__mean, self)

Lognormal$variance <- function() .Call(wrap__Lognormal__variance, self)

Lognormal$cdf <- function(x) .Call(wrap__Lognormal__cdf, self, x)

Lognormal$quantile <- function(p) .Call(wrap__Lognormal__quantile, self, p)

Lognormal$lev <- function(limit) .Call(wrap__Lognormal__lev, self, limit)

Lognormal$stop_loss <- function(retention) .Call(wrap__Lognormal__stop_loss, self, retention)

Lognormal$layer <- function(limit, attachment) .Call(wrap__Lognormal__layer, self, limit, attachment)

Lognormal$sample <- function(n, seed, stream) .Call(wrap__Lognormal__sample, self, n, seed, stream)

#' @export
`$.Lognormal` <- function (self, name) { func <- Lognormal[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Lognormal` <- `$.Lognormal`

Poisson <- new.env(parent = emptyenv())

Poisson$new <- function(lambda) .Call(wrap__Poisson__new, lambda)

Poisson$lambda <- function() .Call(wrap__Poisson__lambda, self)

Poisson$pmf <- function(k) .Call(wrap__Poisson__pmf, self, k)

Poisson$cdf <- function(k) .Call(wrap__Poisson__cdf, self, k)

Poisson$mean <- function() .Call(wrap__Poisson__mean, self)

Poisson$variance <- function() .Call(wrap__Poisson__variance, self)

Poisson$quantile <- function(p) .Call(wrap__Poisson__quantile, self, p)

Poisson$sample <- function(n, seed, stream) .Call(wrap__Poisson__sample, self, n, seed, stream)

#' @export
`$.Poisson` <- function (self, name) { func <- Poisson[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Poisson` <- `$.Poisson`

NegativeBinomial <- new.env(parent = emptyenv())

NegativeBinomial$new <- function(r, beta) .Call(wrap__NegativeBinomial__new, r, beta)

NegativeBinomial$from_mean_variance <- function(mean, variance) .Call(wrap__NegativeBinomial__from_mean_variance, mean, variance)

NegativeBinomial$r <- function() .Call(wrap__NegativeBinomial__r, self)

NegativeBinomial$beta <- function() .Call(wrap__NegativeBinomial__beta, self)

NegativeBinomial$pmf <- function(k) .Call(wrap__NegativeBinomial__pmf, self, k)

NegativeBinomial$cdf <- function(k) .Call(wrap__NegativeBinomial__cdf, self, k)

NegativeBinomial$mean <- function() .Call(wrap__NegativeBinomial__mean, self)

NegativeBinomial$variance <- function() .Call(wrap__NegativeBinomial__variance, self)

NegativeBinomial$quantile <- function(p) .Call(wrap__NegativeBinomial__quantile, self, p)

NegativeBinomial$sample <- function(n, seed, stream) .Call(wrap__NegativeBinomial__sample, self, n, seed, stream)

#' @export
`$.NegativeBinomial` <- function (self, name) { func <- NegativeBinomial[[name]]; environment(func) <- environment(); func }

#' @export
`[[.NegativeBinomial` <- `$.NegativeBinomial`

Grid <- new.env(parent = emptyenv())

Grid$new <- function(step, probs) .Call(wrap__Grid__new, step, probs)

Grid$discretize <- function(severity, step, points, method) .Call(wrap__Grid__discretize, severity, step, points, method)

Grid$step <- function() .Call(wrap__Grid__step, self)

Grid$probs <- function() .Call(wrap__Grid__probs, self)

Grid$map <- function(f) .Call(wrap__Grid__map, self, f)

Grid$report <- function() .Call(wrap__Grid__report, self)

Grid$mean <- function() .Call(wrap__Grid__mean, self)

Grid$variance <- function() .Call(wrap__Grid__variance, self)

Grid$cdf <- function(x) .Call(wrap__Grid__cdf, self, x)

Grid$quantile <- function(p) .Call(wrap__Grid__quantile, self, p)

Grid$lev <- function(limit) .Call(wrap__Grid__lev, self, limit)

Grid$stop_loss <- function(retention) .Call(wrap__Grid__stop_loss, self, retention)

Grid$layer <- function(limit, attachment) .Call(wrap__Grid__layer, self, limit, attachment)

#' @export
`$.Grid` <- function (self, name) { func <- Grid[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Grid` <- `$.Grid`

Sampled <- new.env(parent = emptyenv())

Sampled$new <- function(draws) .Call(wrap__Sampled__new, draws)

Sampled$draws <- function() .Call(wrap__Sampled__draws, self)

Sampled$mean <- function() .Call(wrap__Sampled__mean, self)

Sampled$variance <- function() .Call(wrap__Sampled__variance, self)

Sampled$cdf <- function(x) .Call(wrap__Sampled__cdf, self, x)

Sampled$quantile <- function(p) .Call(wrap__Sampled__quantile, self, p)

Sampled$var <- function(p) .Call(wrap__Sampled__var, self, p)

Sampled$tvar <- function(p) .Call(wrap__Sampled__tvar, self, p)

#' @export
`$.Sampled` <- function (self, name) { func <- Sampled[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Sampled` <- `$.Sampled`

PredictiveDistribution <- new.env(parent = emptyenv())

PredictiveDistribution$new <- function(dims, keys, draws, n_sims) .Call(wrap__PredictiveDistribution__new, dims, keys, draws, n_sims)

PredictiveDistribution$dims <- function() .Call(wrap__PredictiveDistribution__dims, self)

PredictiveDistribution$n_sims <- function() .Call(wrap__PredictiveDistribution__n_sims, self)

PredictiveDistribution$n_components <- function() .Call(wrap__PredictiveDistribution__n_components, self)

PredictiveDistribution$keys <- function() .Call(wrap__PredictiveDistribution__keys, self)

PredictiveDistribution$draw_matrix <- function() .Call(wrap__PredictiveDistribution__draw_matrix, self)

PredictiveDistribution$marginal <- function(key) .Call(wrap__PredictiveDistribution__marginal, self, key)

PredictiveDistribution$aggregate <- function(keep) .Call(wrap__PredictiveDistribution__aggregate, self, keep)

PredictiveDistribution$total <- function() .Call(wrap__PredictiveDistribution__total, self)

PredictiveDistribution$mean <- function() .Call(wrap__PredictiveDistribution__mean, self)

PredictiveDistribution$variance <- function() .Call(wrap__PredictiveDistribution__variance, self)

PredictiveDistribution$quantile <- function(p) .Call(wrap__PredictiveDistribution__quantile, self, p)

PredictiveDistribution$var <- function(p) .Call(wrap__PredictiveDistribution__var, self, p)

PredictiveDistribution$tvar <- function(p) .Call(wrap__PredictiveDistribution__tvar, self, p)

PredictiveDistribution$provenance <- function() .Call(wrap__PredictiveDistribution__provenance, self)

#' @export
`$.PredictiveDistribution` <- function (self, name) { func <- PredictiveDistribution[[name]]; environment(func) <- environment(); func }

#' @export
`[[.PredictiveDistribution` <- `$.PredictiveDistribution`

StackingModel <- new.env(parent = emptyenv())

StackingModel$weights <- function(x, p) .Call(wrap__StackingModel__weights, self, x, p)

StackingModel$alpha_draws <- function() .Call(wrap__StackingModel__alpha_draws, self)

StackingModel$beta_draws <- function() .Call(wrap__StackingModel__beta_draws, self)

StackingModel$divergences <- function() .Call(wrap__StackingModel__divergences, self)

StackingModel$rhat_ess <- function() .Call(wrap__StackingModel__rhat_ess, self)

#' @export
`$.StackingModel` <- function (self, name) { func <- StackingModel[[name]]; environment(func) <- environment(); func }

#' @export
`[[.StackingModel` <- `$.StackingModel`

BayesGlmModel <- new.env(parent = emptyenv())

BayesGlmModel$names <- function() .Call(wrap__BayesGlmModel__names, self)

BayesGlmModel$posterior_mean <- function() .Call(wrap__BayesGlmModel__posterior_mean, self)

BayesGlmModel$coefficient_draws <- function() .Call(wrap__BayesGlmModel__coefficient_draws, self)

BayesGlmModel$dispersion_draws <- function() .Call(wrap__BayesGlmModel__dispersion_draws, self)

BayesGlmModel$chains <- function() .Call(wrap__BayesGlmModel__chains, self)

BayesGlmModel$divergences <- function() .Call(wrap__BayesGlmModel__divergences, self)

BayesGlmModel$summary <- function() .Call(wrap__BayesGlmModel__summary, self)

BayesGlmModel$loo <- function() .Call(wrap__BayesGlmModel__loo, self)

BayesGlmModel$log_likelihood <- function() .Call(wrap__BayesGlmModel__log_likelihood, self)

BayesGlmModel$predict <- function(x, names, offset) .Call(wrap__BayesGlmModel__predict, self, x, names, offset)

BayesGlmModel$predict_distribution <- function(x, names, offset, weights, n_sims, seed) .Call(wrap__BayesGlmModel__predict_distribution, self, x, names, offset, weights, n_sims, seed)

#' @export
`$.BayesGlmModel` <- function (self, name) { func <- BayesGlmModel[[name]]; environment(func) <- environment(); func }

#' @export
`[[.BayesGlmModel` <- `$.BayesGlmModel`

GlmModel <- new.env(parent = emptyenv())

GlmModel$names <- function() .Call(wrap__GlmModel__names, self)

GlmModel$coefficients <- function() .Call(wrap__GlmModel__coefficients, self)

GlmModel$std_errors <- function() .Call(wrap__GlmModel__std_errors, self)

GlmModel$p_values <- function() .Call(wrap__GlmModel__p_values, self)

GlmModel$covariance <- function() .Call(wrap__GlmModel__covariance, self)

GlmModel$robust_covariance <- function(kind, groups) .Call(wrap__GlmModel__robust_covariance, self, kind, groups)

GlmModel$to_json <- function() .Call(wrap__GlmModel__to_json, self)

GlmModel$from_json <- function(text) .Call(wrap__GlmModel__from_json, text)

GlmModel$input_hash <- function() .Call(wrap__GlmModel__input_hash, self)

GlmModel$dispersion <- function() .Call(wrap__GlmModel__dispersion, self)

GlmModel$deviance <- function() .Call(wrap__GlmModel__deviance, self)

GlmModel$null_deviance <- function() .Call(wrap__GlmModel__null_deviance, self)

GlmModel$log_likelihood <- function() .Call(wrap__GlmModel__log_likelihood, self)

GlmModel$aic <- function() .Call(wrap__GlmModel__aic, self)

GlmModel$df_resid <- function() .Call(wrap__GlmModel__df_resid, self)

GlmModel$iterations <- function() .Call(wrap__GlmModel__iterations, self)

GlmModel$fitted <- function() .Call(wrap__GlmModel__fitted, self)

GlmModel$family <- function() .Call(wrap__GlmModel__family, self)

GlmModel$predict <- function(x, names, offset) .Call(wrap__GlmModel__predict, self, x, names, offset)

GlmModel$predict_distribution <- function(x, names, offset, weights, n_sims, seed, parameters) .Call(wrap__GlmModel__predict_distribution, self, x, names, offset, weights, n_sims, seed, parameters)

#' @export
`$.GlmModel` <- function (self, name) { func <- GlmModel[[name]]; environment(func) <- environment(); func }

#' @export
`[[.GlmModel` <- `$.GlmModel`

ElasticNetPath <- new.env(parent = emptyenv())

ElasticNetPath$names <- function() .Call(wrap__ElasticNetPath__names, self)

ElasticNetPath$to_json <- function() .Call(wrap__ElasticNetPath__to_json, self)

ElasticNetPath$from_json <- function(texts) .Call(wrap__ElasticNetPath__from_json, texts)

ElasticNetPath$lambda <- function() .Call(wrap__ElasticNetPath__lambda, self)

ElasticNetPath$coefficients <- function() .Call(wrap__ElasticNetPath__coefficients, self)

ElasticNetPath$deviance <- function() .Call(wrap__ElasticNetPath__deviance, self)

ElasticNetPath$deviance_ratio <- function() .Call(wrap__ElasticNetPath__deviance_ratio, self)

ElasticNetPath$df <- function() .Call(wrap__ElasticNetPath__df, self)

ElasticNetPath$null_deviance <- function() .Call(wrap__ElasticNetPath__null_deviance, self)

ElasticNetPath$alpha <- function() .Call(wrap__ElasticNetPath__alpha, self)

ElasticNetPath$family <- function() .Call(wrap__ElasticNetPath__family, self)

ElasticNetPath$predict <- function(index, x, names, offset) .Call(wrap__ElasticNetPath__predict, self, index, x, names, offset)

ElasticNetPath$predict_distribution <- function(index, x, names, offset, weights, n_sims, seed) .Call(wrap__ElasticNetPath__predict_distribution, self, index, x, names, offset, weights, n_sims, seed)

#' @export
`$.ElasticNetPath` <- function (self, name) { func <- ElasticNetPath[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ElasticNetPath` <- `$.ElasticNetPath`

GamModel <- new.env(parent = emptyenv())

GamModel$names <- function() .Call(wrap__GamModel__names, self)

GamModel$to_json <- function() .Call(wrap__GamModel__to_json, self)

GamModel$from_json <- function(text) .Call(wrap__GamModel__from_json, text)

GamModel$coefficients <- function() .Call(wrap__GamModel__coefficients, self)

GamModel$lambdas <- function() .Call(wrap__GamModel__lambdas, self)

GamModel$edf <- function() .Call(wrap__GamModel__edf, self)

GamModel$dispersion <- function() .Call(wrap__GamModel__dispersion, self)

GamModel$deviance <- function() .Call(wrap__GamModel__deviance, self)

GamModel$score <- function() .Call(wrap__GamModel__score, self)

GamModel$fitted <- function() .Call(wrap__GamModel__fitted, self)

GamModel$predict <- function(x, names, offset) .Call(wrap__GamModel__predict, self, x, names, offset)

GamModel$predict_distribution <- function(x, names, offset, weights, n_sims, seed) .Call(wrap__GamModel__predict_distribution, self, x, names, offset, weights, n_sims, seed)

#' @export
`$.GamModel` <- function (self, name) { func <- GamModel[[name]]; environment(func) <- environment(); func }

#' @export
`[[.GamModel` <- `$.GamModel`

Pareto <- new.env(parent = emptyenv())

Pareto$new <- function(t, alpha, truncation_at) .Call(wrap__Pareto__new, t, alpha, truncation_at)

Pareto$fit <- function(losses, t, reporting, censored, weights, truncation_at) .Call(wrap__Pareto__fit, losses, t, reporting, censored, weights, truncation_at)

Pareto$t <- function() .Call(wrap__Pareto__t, self)

Pareto$alpha <- function() .Call(wrap__Pareto__alpha, self)

Pareto$truncation <- function() .Call(wrap__Pareto__truncation, self)

Pareto$mean <- function() .Call(wrap__Pareto__mean, self)

Pareto$variance <- function() .Call(wrap__Pareto__variance, self)

Pareto$cdf <- function(x) .Call(wrap__Pareto__cdf, self, x)

Pareto$survival <- function(x) .Call(wrap__Pareto__survival, self, x)

Pareto$quantile <- function(p) .Call(wrap__Pareto__quantile, self, p)

Pareto$lev <- function(limit) .Call(wrap__Pareto__lev, self, limit)

Pareto$stop_loss <- function(retention) .Call(wrap__Pareto__stop_loss, self, retention)

Pareto$layer <- function(limit, attachment) .Call(wrap__Pareto__layer, self, limit, attachment)

Pareto$layer_variance <- function(limit, attachment) .Call(wrap__Pareto__layer_variance, self, limit, attachment)

Pareto$sample <- function(n, seed, stream) .Call(wrap__Pareto__sample, self, n, seed, stream)

#' @export
`$.Pareto` <- function (self, name) { func <- Pareto[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Pareto` <- `$.Pareto`

PiecewisePareto <- new.env(parent = emptyenv())

PiecewisePareto$new <- function(t, alpha, truncation_at, truncation_type) .Call(wrap__PiecewisePareto__new, t, alpha, truncation_at, truncation_type)

PiecewisePareto$fit <- function(losses, t, reporting, censored, weights, truncation_at, truncation_type) .Call(wrap__PiecewisePareto__fit, losses, t, reporting, censored, weights, truncation_at, truncation_type)

PiecewisePareto$t <- function() .Call(wrap__PiecewisePareto__t, self)

PiecewisePareto$alpha <- function() .Call(wrap__PiecewisePareto__alpha, self)

PiecewisePareto$truncation <- function() .Call(wrap__PiecewisePareto__truncation, self)

PiecewisePareto$truncation_type <- function() .Call(wrap__PiecewisePareto__truncation_type, self)

PiecewisePareto$mean <- function() .Call(wrap__PiecewisePareto__mean, self)

PiecewisePareto$variance <- function() .Call(wrap__PiecewisePareto__variance, self)

PiecewisePareto$cdf <- function(x) .Call(wrap__PiecewisePareto__cdf, self, x)

PiecewisePareto$survival <- function(x) .Call(wrap__PiecewisePareto__survival, self, x)

PiecewisePareto$quantile <- function(p) .Call(wrap__PiecewisePareto__quantile, self, p)

PiecewisePareto$lev <- function(limit) .Call(wrap__PiecewisePareto__lev, self, limit)

PiecewisePareto$stop_loss <- function(retention) .Call(wrap__PiecewisePareto__stop_loss, self, retention)

PiecewisePareto$layer <- function(limit, attachment) .Call(wrap__PiecewisePareto__layer, self, limit, attachment)

PiecewisePareto$layer_variance <- function(limit, attachment) .Call(wrap__PiecewisePareto__layer_variance, self, limit, attachment)

PiecewisePareto$sample <- function(n, seed, stream) .Call(wrap__PiecewisePareto__sample, self, n, seed, stream)

#' @export
`$.PiecewisePareto` <- function (self, name) { func <- PiecewisePareto[[name]]; environment(func) <- environment(); func }

#' @export
`[[.PiecewisePareto` <- `$.PiecewisePareto`

LogAffinePareto <- new.env(parent = emptyenv())

LogAffinePareto$new <- function(t, alpha0, gamma) .Call(wrap__LogAffinePareto__new, t, alpha0, gamma)

LogAffinePareto$from_delta <- function(t, alpha0, delta) .Call(wrap__LogAffinePareto__from_delta, t, alpha0, delta)

LogAffinePareto$t <- function() .Call(wrap__LogAffinePareto__t, self)

LogAffinePareto$alpha0 <- function() .Call(wrap__LogAffinePareto__alpha0, self)

LogAffinePareto$gamma <- function() .Call(wrap__LogAffinePareto__gamma, self)

LogAffinePareto$delta <- function() .Call(wrap__LogAffinePareto__delta, self)

LogAffinePareto$local_alpha <- function(x) .Call(wrap__LogAffinePareto__local_alpha, self, x)

LogAffinePareto$mean <- function() .Call(wrap__LogAffinePareto__mean, self)

LogAffinePareto$variance <- function() .Call(wrap__LogAffinePareto__variance, self)

LogAffinePareto$cdf <- function(x) .Call(wrap__LogAffinePareto__cdf, self, x)

LogAffinePareto$survival <- function(x) .Call(wrap__LogAffinePareto__survival, self, x)

LogAffinePareto$quantile <- function(p) .Call(wrap__LogAffinePareto__quantile, self, p)

LogAffinePareto$lev <- function(limit) .Call(wrap__LogAffinePareto__lev, self, limit)

LogAffinePareto$stop_loss <- function(retention) .Call(wrap__LogAffinePareto__stop_loss, self, retention)

LogAffinePareto$layer <- function(limit, attachment) .Call(wrap__LogAffinePareto__layer, self, limit, attachment)

LogAffinePareto$layer_variance <- function(limit, attachment) .Call(wrap__LogAffinePareto__layer_variance, self, limit, attachment)

LogAffinePareto$sample <- function(n, seed, stream) .Call(wrap__LogAffinePareto__sample, self, n, seed, stream)

#' @export
`$.LogAffinePareto` <- function (self, name) { func <- LogAffinePareto[[name]]; environment(func) <- environment(); func }

#' @export
`[[.LogAffinePareto` <- `$.LogAffinePareto`

GeneralizedPareto <- new.env(parent = emptyenv())

GeneralizedPareto$new <- function(xi, beta, location) .Call(wrap__GeneralizedPareto__new, xi, beta, location)

GeneralizedPareto$riegel <- function(t, alpha_ini, alpha_tail) .Call(wrap__GeneralizedPareto__riegel, t, alpha_ini, alpha_tail)

GeneralizedPareto$fit_riegel <- function(losses, t, reporting, censored, weights) .Call(wrap__GeneralizedPareto__fit_riegel, losses, t, reporting, censored, weights)

GeneralizedPareto$xi <- function() .Call(wrap__GeneralizedPareto__xi, self)

GeneralizedPareto$beta <- function() .Call(wrap__GeneralizedPareto__beta, self)

GeneralizedPareto$location <- function() .Call(wrap__GeneralizedPareto__location, self)

GeneralizedPareto$mean <- function() .Call(wrap__GeneralizedPareto__mean, self)

GeneralizedPareto$variance <- function() .Call(wrap__GeneralizedPareto__variance, self)

GeneralizedPareto$cdf <- function(x) .Call(wrap__GeneralizedPareto__cdf, self, x)

GeneralizedPareto$survival <- function(x) .Call(wrap__GeneralizedPareto__survival, self, x)

GeneralizedPareto$quantile <- function(p) .Call(wrap__GeneralizedPareto__quantile, self, p)

GeneralizedPareto$lev <- function(limit) .Call(wrap__GeneralizedPareto__lev, self, limit)

GeneralizedPareto$stop_loss <- function(retention) .Call(wrap__GeneralizedPareto__stop_loss, self, retention)

GeneralizedPareto$layer <- function(limit, attachment) .Call(wrap__GeneralizedPareto__layer, self, limit, attachment)

GeneralizedPareto$layer_variance <- function(limit, attachment) .Call(wrap__GeneralizedPareto__layer_variance, self, limit, attachment)

GeneralizedPareto$sample <- function(n, seed, stream) .Call(wrap__GeneralizedPareto__sample, self, n, seed, stream)

#' @export
`$.GeneralizedPareto` <- function (self, name) { func <- GeneralizedPareto[[name]]; environment(func) <- environment(); func }

#' @export
`[[.GeneralizedPareto` <- `$.GeneralizedPareto`

GammaDist <- new.env(parent = emptyenv())

GammaDist$new <- function(shape, scale) .Call(wrap__GammaDist__new, shape, scale)

GammaDist$from_mean_cv <- function(mean, cv) .Call(wrap__GammaDist__from_mean_cv, mean, cv)

GammaDist$from_mean_dispersion <- function(mean, dispersion) .Call(wrap__GammaDist__from_mean_dispersion, mean, dispersion)

GammaDist$shape <- function() .Call(wrap__GammaDist__shape, self)

GammaDist$scale <- function() .Call(wrap__GammaDist__scale, self)

GammaDist$ln_pdf <- function(x) .Call(wrap__GammaDist__ln_pdf, self, x)

GammaDist$mean <- function() .Call(wrap__GammaDist__mean, self)

GammaDist$variance <- function() .Call(wrap__GammaDist__variance, self)

GammaDist$cdf <- function(x) .Call(wrap__GammaDist__cdf, self, x)

GammaDist$survival <- function(x) .Call(wrap__GammaDist__survival, self, x)

GammaDist$quantile <- function(p) .Call(wrap__GammaDist__quantile, self, p)

GammaDist$lev <- function(limit) .Call(wrap__GammaDist__lev, self, limit)

GammaDist$stop_loss <- function(retention) .Call(wrap__GammaDist__stop_loss, self, retention)

GammaDist$layer <- function(limit, attachment) .Call(wrap__GammaDist__layer, self, limit, attachment)

GammaDist$layer_variance <- function(limit, attachment) .Call(wrap__GammaDist__layer_variance, self, limit, attachment)

GammaDist$sample <- function(n, seed, stream) .Call(wrap__GammaDist__sample, self, n, seed, stream)

#' @export
`$.GammaDist` <- function (self, name) { func <- GammaDist[[name]]; environment(func) <- environment(); func }

#' @export
`[[.GammaDist` <- `$.GammaDist`

TweedieDist <- new.env(parent = emptyenv())

TweedieDist$new <- function(mean, dispersion, power) .Call(wrap__TweedieDist__new, mean, dispersion, power)

TweedieDist$from_poisson_gamma <- function(lambda, shape, scale) .Call(wrap__TweedieDist__from_poisson_gamma, lambda, shape, scale)

TweedieDist$dispersion <- function() .Call(wrap__TweedieDist__dispersion, self)

TweedieDist$power <- function() .Call(wrap__TweedieDist__power, self)

TweedieDist$lambda <- function() .Call(wrap__TweedieDist__lambda, self)

TweedieDist$severity <- function() .Call(wrap__TweedieDist__severity, self)

TweedieDist$ln_pdf <- function(x) .Call(wrap__TweedieDist__ln_pdf, self, x)

TweedieDist$mean <- function() .Call(wrap__TweedieDist__mean, self)

TweedieDist$variance <- function() .Call(wrap__TweedieDist__variance, self)

TweedieDist$cdf <- function(x) .Call(wrap__TweedieDist__cdf, self, x)

TweedieDist$survival <- function(x) .Call(wrap__TweedieDist__survival, self, x)

TweedieDist$quantile <- function(p) .Call(wrap__TweedieDist__quantile, self, p)

TweedieDist$lev <- function(limit) .Call(wrap__TweedieDist__lev, self, limit)

TweedieDist$stop_loss <- function(retention) .Call(wrap__TweedieDist__stop_loss, self, retention)

TweedieDist$layer <- function(limit, attachment) .Call(wrap__TweedieDist__layer, self, limit, attachment)

TweedieDist$layer_variance <- function(limit, attachment) .Call(wrap__TweedieDist__layer_variance, self, limit, attachment)

TweedieDist$sample <- function(n, seed, stream) .Call(wrap__TweedieDist__sample, self, n, seed, stream)

#' @export
`$.TweedieDist` <- function (self, name) { func <- TweedieDist[[name]]; environment(func) <- environment(); func }

#' @export
`[[.TweedieDist` <- `$.TweedieDist`

CustomDist <- new.env(parent = emptyenv())

CustomDist$new <- function(cdf, quantile, name) .Call(wrap__CustomDist__new, cdf, quantile, name)

CustomDist$name <- function() .Call(wrap__CustomDist__name, self)

CustomDist$has_quantile <- function() .Call(wrap__CustomDist__has_quantile, self)

CustomDist$upper <- function() .Call(wrap__CustomDist__upper, self)

CustomDist$last_error <- function() .Call(wrap__CustomDist__last_error, self)

CustomDist$mean <- function() .Call(wrap__CustomDist__mean, self)

CustomDist$variance <- function() .Call(wrap__CustomDist__variance, self)

CustomDist$cdf <- function(x) .Call(wrap__CustomDist__cdf, self, x)

CustomDist$survival <- function(x) .Call(wrap__CustomDist__survival, self, x)

CustomDist$quantile <- function(p) .Call(wrap__CustomDist__quantile, self, p)

CustomDist$lev <- function(limit) .Call(wrap__CustomDist__lev, self, limit)

CustomDist$stop_loss <- function(retention) .Call(wrap__CustomDist__stop_loss, self, retention)

CustomDist$layer <- function(limit, attachment) .Call(wrap__CustomDist__layer, self, limit, attachment)

CustomDist$layer_variance <- function(limit, attachment) .Call(wrap__CustomDist__layer_variance, self, limit, attachment)

CustomDist$sample <- function(n, seed, stream) .Call(wrap__CustomDist__sample, self, n, seed, stream)

#' @export
`$.CustomDist` <- function (self, name) { func <- CustomDist[[name]]; environment(func) <- environment(); func }

#' @export
`[[.CustomDist` <- `$.CustomDist`

WeibullDist <- new.env(parent = emptyenv())

WeibullDist$new <- function(shape, scale) .Call(wrap__WeibullDist__new, shape, scale)

WeibullDist$shape <- function() .Call(wrap__WeibullDist__shape, self)

WeibullDist$scale <- function() .Call(wrap__WeibullDist__scale, self)

WeibullDist$mean <- function() .Call(wrap__WeibullDist__mean, self)

WeibullDist$variance <- function() .Call(wrap__WeibullDist__variance, self)

WeibullDist$cdf <- function(x) .Call(wrap__WeibullDist__cdf, self, x)

WeibullDist$survival <- function(x) .Call(wrap__WeibullDist__survival, self, x)

WeibullDist$quantile <- function(p) .Call(wrap__WeibullDist__quantile, self, p)

WeibullDist$lev <- function(limit) .Call(wrap__WeibullDist__lev, self, limit)

WeibullDist$stop_loss <- function(retention) .Call(wrap__WeibullDist__stop_loss, self, retention)

WeibullDist$layer <- function(limit, attachment) .Call(wrap__WeibullDist__layer, self, limit, attachment)

WeibullDist$layer_variance <- function(limit, attachment) .Call(wrap__WeibullDist__layer_variance, self, limit, attachment)

WeibullDist$sample <- function(n, seed, stream) .Call(wrap__WeibullDist__sample, self, n, seed, stream)

#' @export
`$.WeibullDist` <- function (self, name) { func <- WeibullDist[[name]]; environment(func) <- environment(); func }

#' @export
`[[.WeibullDist` <- `$.WeibullDist`

LoglogisticDist <- new.env(parent = emptyenv())

LoglogisticDist$new <- function(shape, scale) .Call(wrap__LoglogisticDist__new, shape, scale)

LoglogisticDist$shape <- function() .Call(wrap__LoglogisticDist__shape, self)

LoglogisticDist$scale <- function() .Call(wrap__LoglogisticDist__scale, self)

LoglogisticDist$mean <- function() .Call(wrap__LoglogisticDist__mean, self)

LoglogisticDist$variance <- function() .Call(wrap__LoglogisticDist__variance, self)

LoglogisticDist$cdf <- function(x) .Call(wrap__LoglogisticDist__cdf, self, x)

LoglogisticDist$survival <- function(x) .Call(wrap__LoglogisticDist__survival, self, x)

LoglogisticDist$quantile <- function(p) .Call(wrap__LoglogisticDist__quantile, self, p)

LoglogisticDist$lev <- function(limit) .Call(wrap__LoglogisticDist__lev, self, limit)

LoglogisticDist$stop_loss <- function(retention) .Call(wrap__LoglogisticDist__stop_loss, self, retention)

LoglogisticDist$layer <- function(limit, attachment) .Call(wrap__LoglogisticDist__layer, self, limit, attachment)

LoglogisticDist$layer_variance <- function(limit, attachment) .Call(wrap__LoglogisticDist__layer_variance, self, limit, attachment)

LoglogisticDist$sample <- function(n, seed, stream) .Call(wrap__LoglogisticDist__sample, self, n, seed, stream)

#' @export
`$.LoglogisticDist` <- function (self, name) { func <- LoglogisticDist[[name]]; environment(func) <- environment(); func }

#' @export
`[[.LoglogisticDist` <- `$.LoglogisticDist`

MixtureDist <- new.env(parent = emptyenv())

MixtureDist$new <- function(weights, components) .Call(wrap__MixtureDist__new, weights, components)

MixtureDist$weights <- function() .Call(wrap__MixtureDist__weights, self)

MixtureDist$mean <- function() .Call(wrap__MixtureDist__mean, self)

MixtureDist$variance <- function() .Call(wrap__MixtureDist__variance, self)

MixtureDist$cdf <- function(x) .Call(wrap__MixtureDist__cdf, self, x)

MixtureDist$survival <- function(x) .Call(wrap__MixtureDist__survival, self, x)

MixtureDist$quantile <- function(p) .Call(wrap__MixtureDist__quantile, self, p)

MixtureDist$lev <- function(limit) .Call(wrap__MixtureDist__lev, self, limit)

MixtureDist$stop_loss <- function(retention) .Call(wrap__MixtureDist__stop_loss, self, retention)

MixtureDist$layer <- function(limit, attachment) .Call(wrap__MixtureDist__layer, self, limit, attachment)

MixtureDist$layer_variance <- function(limit, attachment) .Call(wrap__MixtureDist__layer_variance, self, limit, attachment)

MixtureDist$sample <- function(n, seed, stream) .Call(wrap__MixtureDist__sample, self, n, seed, stream)

#' @export
`$.MixtureDist` <- function (self, name) { func <- MixtureDist[[name]]; environment(func) <- environment(); func }

#' @export
`[[.MixtureDist` <- `$.MixtureDist`

Binomial <- new.env(parent = emptyenv())

Binomial$new <- function(n, p) .Call(wrap__Binomial__new, n, p)

Binomial$n <- function() .Call(wrap__Binomial__n, self)

Binomial$p <- function() .Call(wrap__Binomial__p, self)

Binomial$pmf <- function(k) .Call(wrap__Binomial__pmf, self, k)

Binomial$cdf <- function(k) .Call(wrap__Binomial__cdf, self, k)

Binomial$mean <- function() .Call(wrap__Binomial__mean, self)

Binomial$variance <- function() .Call(wrap__Binomial__variance, self)

Binomial$quantile <- function(p) .Call(wrap__Binomial__quantile, self, p)

Binomial$sample <- function(n, seed, stream) .Call(wrap__Binomial__sample, self, n, seed, stream)

#' @export
`$.Binomial` <- function (self, name) { func <- Binomial[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Binomial` <- `$.Binomial`

NaturalPortfolio <- new.env(parent = emptyenv())

NaturalPortfolio$from_rows <- function(units, x, probs) .Call(wrap__NaturalPortfolio__from_rows, units, x, probs)

NaturalPortfolio$from_predictive <- function(pd) .Call(wrap__NaturalPortfolio__from_predictive, pd)

NaturalPortfolio$from_independent <- function(units, grids) .Call(wrap__NaturalPortfolio__from_independent, units, grids)

NaturalPortfolio$units <- function() .Call(wrap__NaturalPortfolio__units, self)

NaturalPortfolio$totals <- function() .Call(wrap__NaturalPortfolio__totals, self)

NaturalPortfolio$probs <- function() .Call(wrap__NaturalPortfolio__probs, self)

NaturalPortfolio$kappa <- function(i) .Call(wrap__NaturalPortfolio__kappa, self, i)

NaturalPortfolio$expected <- function() .Call(wrap__NaturalPortfolio__expected, self)

NaturalPortfolio$assets <- function(p) .Call(wrap__NaturalPortfolio__assets, self, p)

NaturalPortfolio$max <- function() .Call(wrap__NaturalPortfolio__max, self)

NaturalPortfolio$price <- function(distortion, assets, allocation) .Call(wrap__NaturalPortfolio__price, self, distortion, assets, allocation)

NaturalPortfolio$calibrate <- function(family, assets, target, value, r0) .Call(wrap__NaturalPortfolio__calibrate, self, family, assets, target, value, r0)

NaturalPortfolio$bodoff <- function(assets) .Call(wrap__NaturalPortfolio__bodoff, self, assets)

NaturalPortfolio$epd <- function(assets) .Call(wrap__NaturalPortfolio__epd, self, assets)

NaturalPortfolio$assets_for_epd <- function(epd) .Call(wrap__NaturalPortfolio__assets_for_epd, self, epd)

#' @export
`$.NaturalPortfolio` <- function (self, name) { func <- NaturalPortfolio[[name]]; environment(func) <- environment(); func }

#' @export
`[[.NaturalPortfolio` <- `$.NaturalPortfolio`

CollectiveModel <- new.env(parent = emptyenv())

CollectiveModel$new <- function(frequency, severity) .Call(wrap__CollectiveModel__new, frequency, severity)

CollectiveModel$excess_frequency <- function(x) .Call(wrap__CollectiveModel__excess_frequency, self, x)

CollectiveModel$layer_mean <- function(limit, attachment) .Call(wrap__CollectiveModel__layer_mean, self, limit, attachment)

CollectiveModel$layer_variance <- function(limit, attachment) .Call(wrap__CollectiveModel__layer_variance, self, limit, attachment)

CollectiveModel$mean <- function() .Call(wrap__CollectiveModel__mean, self)

CollectiveModel$variance <- function() .Call(wrap__CollectiveModel__variance, self)

CollectiveModel$simulate <- function(n_sims, seed) .Call(wrap__CollectiveModel__simulate, self, n_sims, seed)

#' @export
`$.CollectiveModel` <- function (self, name) { func <- CollectiveModel[[name]]; environment(func) <- environment(); func }

#' @export
`[[.CollectiveModel` <- `$.CollectiveModel`

TowerModel <- new.env(parent = emptyenv())

TowerModel$frequency <- function() .Call(wrap__TowerModel__frequency, self)

TowerModel$severity <- function() .Call(wrap__TowerModel__severity, self)

TowerModel$excess_frequency <- function(x) .Call(wrap__TowerModel__excess_frequency, self, x)

TowerModel$layer_loss <- function(limit, attachment) .Call(wrap__TowerModel__layer_loss, self, limit, attachment)

TowerModel$match_tower <- function(attachments, layer_losses, frequencies, rule_name) .Call(wrap__TowerModel__match_tower, attachments, layer_losses, frequencies, rule_name)

TowerModel$fit_pml_curve <- function(return_periods, amounts, tail_alpha, truncation_at) .Call(wrap__TowerModel__fit_pml_curve, return_periods, amounts, tail_alpha, truncation_at)

TowerModel$fit_references <- function(limits, attachments, losses, thresholds, frequencies, default_alpha, rule_name) .Call(wrap__TowerModel__fit_references, limits, attachments, losses, thresholds, frequencies, default_alpha, rule_name)

#' @export
`$.TowerModel` <- function (self, name) { func <- TowerModel[[name]]; environment(func) <- environment(); func }

#' @export
`[[.TowerModel` <- `$.TowerModel`

Mbbefd <- new.env(parent = emptyenv())

Mbbefd$new <- function(b, g) .Call(wrap__Mbbefd__new, b, g)

Mbbefd$swiss_re <- function(c) .Call(wrap__Mbbefd__swiss_re, c)

Mbbefd$b <- function() .Call(wrap__Mbbefd__b, self)

Mbbefd$g <- function() .Call(wrap__Mbbefd__g, self)

Mbbefd$curve <- function(x) .Call(wrap__Mbbefd__curve, self, x)

Mbbefd$cdf <- function(x) .Call(wrap__Mbbefd__cdf, self, x)

Mbbefd$mean <- function() .Call(wrap__Mbbefd__mean, self)

Mbbefd$total_loss_probability <- function() .Call(wrap__Mbbefd__total_loss_probability, self)

Mbbefd$layer_share <- function(limit, attachment, mpl) .Call(wrap__Mbbefd__layer_share, self, limit, attachment, mpl)

Mbbefd$rate_quantile <- function(u) .Call(wrap__Mbbefd__rate_quantile, self, u)

#' @export
`$.Mbbefd` <- function (self, name) { func <- Mbbefd[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Mbbefd` <- `$.Mbbefd`

Tabulated <- new.env(parent = emptyenv())

Tabulated$new <- function(x, g) .Call(wrap__Tabulated__new, x, g)

Tabulated$x <- function() .Call(wrap__Tabulated__x, self)

Tabulated$g <- function() .Call(wrap__Tabulated__g, self)

Tabulated$curve <- function(x) .Call(wrap__Tabulated__curve, self, x)

Tabulated$mean <- function() .Call(wrap__Tabulated__mean, self)

Tabulated$layer_share <- function(limit, attachment, mpl) .Call(wrap__Tabulated__layer_share, self, limit, attachment, mpl)

Tabulated$rate_quantile <- function(u) .Call(wrap__Tabulated__rate_quantile, self, u)

#' @export
`$.Tabulated` <- function (self, name) { func <- Tabulated[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Tabulated` <- `$.Tabulated`

RiskProfile <- new.env(parent = emptyenv())

RiskProfile$new <- function(sums_insured, risks, curves, expected_losses, premiums, loss_ratio, lower, upper, tilted) .Call(wrap__RiskProfile__new, sums_insured, risks, curves, expected_losses, premiums, loss_ratio, lower, upper, tilted)

RiskProfile$expected_loss <- function() .Call(wrap__RiskProfile__expected_loss, self)

RiskProfile$expected_claims <- function() .Call(wrap__RiskProfile__expected_claims, self)

RiskProfile$expected_layer_loss <- function(limit, attachment, surplus_retention, surplus_lines) .Call(wrap__RiskProfile__expected_layer_loss, self, limit, attachment, surplus_retention, surplus_lines)

RiskProfile$expected_surplus_loss <- function(retention, lines) .Call(wrap__RiskProfile__expected_surplus_loss, self, retention, lines)

RiskProfile$simulate <- function(n_sims, seed) .Call(wrap__RiskProfile__simulate, self, n_sims, seed)

#' @export
`$.RiskProfile` <- function (self, name) { func <- RiskProfile[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RiskProfile` <- `$.RiskProfile`

Triangle <- new.env(parent = emptyenv())

Triangle$from_long <- function(key_names, keys, origin_year, origin_month, ages, valuation_year, valuation_month, development_is_valuation, names, values, origin_grain, development_grain, cumulative) .Call(wrap__Triangle__from_long, key_names, keys, origin_year, origin_month, ages, valuation_year, valuation_month, development_is_valuation, names, values, origin_grain, development_grain, cumulative)

Triangle$shape <- function() .Call(wrap__Triangle__shape, self)

Triangle$keys <- function() .Call(wrap__Triangle__keys, self)

Triangle$index <- function() .Call(wrap__Triangle__index, self)

Triangle$index_names <- function() .Call(wrap__Triangle__index_names, self)

Triangle$columns <- function() .Call(wrap__Triangle__columns, self)

Triangle$origins <- function() .Call(wrap__Triangle__origins, self)

Triangle$development <- function() .Call(wrap__Triangle__development, self)

Triangle$origin_grain <- function() .Call(wrap__Triangle__origin_grain, self)

Triangle$development_grain <- function() .Call(wrap__Triangle__development_grain, self)

Triangle$valuation <- function() .Call(wrap__Triangle__valuation, self)

Triangle$is_cumulative <- function() .Call(wrap__Triangle__is_cumulative, self)

Triangle$values <- function() .Call(wrap__Triangle__values, self)

Triangle$to_long <- function() .Call(wrap__Triangle__to_long, self)

Triangle$to_incremental <- function() .Call(wrap__Triangle__to_incremental, self)

Triangle$to_cumulative <- function() .Call(wrap__Triangle__to_cumulative, self)

Triangle$latest_diagonal <- function() .Call(wrap__Triangle__latest_diagonal, self)

Triangle$link_ratios <- function() .Call(wrap__Triangle__link_ratios, self)

Triangle$select <- function(keys, values, columns) .Call(wrap__Triangle__select, self, keys, values, columns)

Triangle$group_by <- function(keys) .Call(wrap__Triangle__group_by, self, keys)

Triangle$grain <- function(origin_grain, development_grain) .Call(wrap__Triangle__grain, self, origin_grain, development_grain)

Triangle$view <- function(keys, values, column) .Call(wrap__Triangle__view, self, keys, values, column)

Triangle$summary <- function() .Call(wrap__Triangle__summary, self)

Triangle$to_text <- function(max_rows, max_cols) .Call(wrap__Triangle__to_text, self, max_rows, max_cols)

Triangle$chain_ladder <- function(column, average, sigma_interpolation, tail) .Call(wrap__Triangle__chain_ladder, self, column, average, sigma_interpolation, tail)

Triangle$mack <- function(column, average, sigma_interpolation, tail, tail_sigma, tail_std_err) .Call(wrap__Triangle__mack, self, column, average, sigma_interpolation, tail, tail_sigma, tail_std_err)

Triangle$expected_loss <- function(column, exposure, apriori, average, sigma_interpolation, tail) .Call(wrap__Triangle__expected_loss, self, column, exposure, apriori, average, sigma_interpolation, tail)

Triangle$bornhuetter_ferguson <- function(column, exposure, apriori, average, sigma_interpolation, tail) .Call(wrap__Triangle__bornhuetter_ferguson, self, column, exposure, apriori, average, sigma_interpolation, tail)

Triangle$benktander <- function(column, exposure, apriori, n_iters, average, sigma_interpolation, tail) .Call(wrap__Triangle__benktander, self, column, exposure, apriori, n_iters, average, sigma_interpolation, tail)

Triangle$cape_cod <- function(column, exposure, trend, decay, average, sigma_interpolation, tail) .Call(wrap__Triangle__cape_cod, self, column, exposure, trend, decay, average, sigma_interpolation, tail)

Triangle$odp_bootstrap <- function(column, n_sims, seed, process) .Call(wrap__Triangle__odp_bootstrap, self, column, n_sims, seed, process)

Triangle$mack_bootstrap <- function(column, n_sims, seed, process, average, sigma_interpolation, centre_residuals) .Call(wrap__Triangle__mack_bootstrap, self, column, n_sims, seed, process, average, sigma_interpolation, centre_residuals)

Triangle$odp_one_year <- function(column, method, exposure, apriori, n_iters, trend, decay, average, sigma_interpolation, tail, n_sims, seed, process) .Call(wrap__Triangle__odp_one_year, self, column, method, exposure, apriori, n_iters, trend, decay, average, sigma_interpolation, tail, n_sims, seed, process)

Triangle$mack_one_year <- function(column, method, exposure, apriori, n_iters, trend, decay, average, sigma_interpolation, tail, n_sims, seed, process, mack_average, mack_sigma_interpolation, centre_residuals) .Call(wrap__Triangle__mack_one_year, self, column, method, exposure, apriori, n_iters, trend, decay, average, sigma_interpolation, tail, n_sims, seed, process, mack_average, mack_sigma_interpolation, centre_residuals)

Triangle$clark_ldf <- function(column, curve, max_age) .Call(wrap__Triangle__clark_ldf, self, column, curve, max_age)

Triangle$clark_cape_cod <- function(column, exposure, curve, max_age) .Call(wrap__Triangle__clark_cape_cod, self, column, exposure, curve, max_age)

#' @export
`$.Triangle` <- function (self, name) { func <- Triangle[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Triangle` <- `$.Triangle`

ReservingTail <- new.env(parent = emptyenv())

ReservingTail$constant <- function(factor, decay, attachment_age) .Call(wrap__ReservingTail__constant, factor, decay, attachment_age)

ReservingTail$curve <- function(curve, fit_from, fit_to, extrap_periods, attachment_age) .Call(wrap__ReservingTail__curve, curve, fit_from, fit_to, extrap_periods, attachment_age)

ReservingTail$bondy <- function(earliest_age, attachment_age) .Call(wrap__ReservingTail__bondy, earliest_age, attachment_age)

ReservingTail$log_linear <- function() .Call(wrap__ReservingTail__log_linear)

ReservingTail$kind <- function() .Call(wrap__ReservingTail__kind, self)

ReservingTail$params <- function() .Call(wrap__ReservingTail__params, self)

#' @export
`$.ReservingTail` <- function (self, name) { func <- ReservingTail[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ReservingTail` <- `$.ReservingTail`

ChainLadderFit <- new.env(parent = emptyenv())

ChainLadderFit$n_segments <- function() .Call(wrap__ChainLadderFit__n_segments, self)

ChainLadderFit$keys <- function() .Call(wrap__ChainLadderFit__keys, self)


ChainLadderFit$row_segments <- function() .Call(wrap__ChainLadderFit__row_segments, self)

ChainLadderFit$origins <- function() .Call(wrap__ChainLadderFit__origins, self)

ChainLadderFit$development <- function() .Call(wrap__ChainLadderFit__development, self)

ChainLadderFit$ldf <- function() .Call(wrap__ChainLadderFit__ldf, self)

ChainLadderFit$sigma <- function() .Call(wrap__ChainLadderFit__sigma, self)

ChainLadderFit$std_err <- function() .Call(wrap__ChainLadderFit__std_err, self)

ChainLadderFit$alpha <- function() .Call(wrap__ChainLadderFit__alpha, self)

ChainLadderFit$estimated_ldf <- function() .Call(wrap__ChainLadderFit__estimated_ldf, self)

ChainLadderFit$tail_attachment_age <- function() .Call(wrap__ChainLadderFit__tail_attachment_age, self)

ChainLadderFit$tail <-function() .Call(wrap__ChainLadderFit__tail, self)

ChainLadderFit$tail_ldf <- function() .Call(wrap__ChainLadderFit__tail_ldf, self)

ChainLadderFit$tail_sigma <- function() .Call(wrap__ChainLadderFit__tail_sigma, self)

ChainLadderFit$tail_std_err <- function() .Call(wrap__ChainLadderFit__tail_std_err, self)

ChainLadderFit$cdf <- function() .Call(wrap__ChainLadderFit__cdf, self)

ChainLadderFit$latest <- function() .Call(wrap__ChainLadderFit__latest, self)

ChainLadderFit$ultimate <- function() .Call(wrap__ChainLadderFit__ultimate, self)

ChainLadderFit$reserve <- function() .Call(wrap__ChainLadderFit__reserve, self)

ChainLadderFit$total_ultimate <- function() .Call(wrap__ChainLadderFit__total_ultimate, self)

ChainLadderFit$total_reserve <- function() .Call(wrap__ChainLadderFit__total_reserve, self)

ChainLadderFit$long_table <- function() .Call(wrap__ChainLadderFit__long_table, self)

ChainLadderFit$totals_table <- function() .Call(wrap__ChainLadderFit__totals_table, self)

ChainLadderFit$development_table <- function() .Call(wrap__ChainLadderFit__development_table, self)

ChainLadderFit$segment <- function(keys, values) .Call(wrap__ChainLadderFit__segment, self, keys, values)

#' @export
`$.ChainLadderFit` <- function (self, name) { func <- ChainLadderFit[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ChainLadderFit` <- `$.ChainLadderFit`

MackFit <- new.env(parent = emptyenv())

MackFit$chain_ladder <- function() .Call(wrap__MackFit__chain_ladder, self)

MackFit$process_risk <- function() .Call(wrap__MackFit__process_risk, self)

MackFit$parameter_risk <- function() .Call(wrap__MackFit__parameter_risk, self)

MackFit$standard_error <- function() .Call(wrap__MackFit__standard_error, self)

MackFit$total_process_risk <- function() .Call(wrap__MackFit__total_process_risk, self)

MackFit$total_parameter_risk <- function() .Call(wrap__MackFit__total_parameter_risk, self)

MackFit$total_standard_error <- function() .Call(wrap__MackFit__total_standard_error, self)

MackFit$total_cv <- function() .Call(wrap__MackFit__total_cv, self)

MackFit$long_table <- function() .Call(wrap__MackFit__long_table, self)

MackFit$totals_table <- function() .Call(wrap__MackFit__totals_table, self)

MackFit$development_table <- function() .Call(wrap__MackFit__development_table, self)

MackFit$segment <- function(keys, values) .Call(wrap__MackFit__segment, self, keys, values)

MackFit$claims_development_result <- function() .Call(wrap__MackFit__claims_development_result, self)

#' @export
`$.MackFit` <- function (self, name) { func <- MackFit[[name]]; environment(func) <- environment(); func }

#' @export
`[[.MackFit` <- `$.MackFit`

ExpectedLossFit <- new.env(parent = emptyenv())

ExpectedLossFit$chain_ladder <- function() .Call(wrap__ExpectedLossFit__chain_ladder, self)

ExpectedLossFit$exposure <- function() .Call(wrap__ExpectedLossFit__exposure, self)

ExpectedLossFit$apriori <- function() .Call(wrap__ExpectedLossFit__apriori, self)

ExpectedLossFit$ultimate <- function() .Call(wrap__ExpectedLossFit__ultimate, self)

ExpectedLossFit$reserve <- function() .Call(wrap__ExpectedLossFit__reserve, self)

ExpectedLossFit$total_ultimate <- function() .Call(wrap__ExpectedLossFit__total_ultimate, self)

ExpectedLossFit$total_reserve <- function() .Call(wrap__ExpectedLossFit__total_reserve, self)

ExpectedLossFit$long_table <- function() .Call(wrap__ExpectedLossFit__long_table, self)

ExpectedLossFit$totals_table <- function() .Call(wrap__ExpectedLossFit__totals_table, self)

ExpectedLossFit$development_table <- function() .Call(wrap__ExpectedLossFit__development_table, self)

ExpectedLossFit$segment <- function(keys, values) .Call(wrap__ExpectedLossFit__segment, self, keys, values)

#' @export
`$.ExpectedLossFit` <- function (self, name) { func <- ExpectedLossFit[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ExpectedLossFit` <- `$.ExpectedLossFit`

CapeCodFit <- new.env(parent = emptyenv())

CapeCodFit$expected_loss <- function() .Call(wrap__CapeCodFit__expected_loss, self)

CapeCodFit$trended_apriori <- function() .Call(wrap__CapeCodFit__trended_apriori, self)

CapeCodFit$long_table <- function() .Call(wrap__CapeCodFit__long_table, self)

CapeCodFit$totals_table <- function() .Call(wrap__CapeCodFit__totals_table, self)

CapeCodFit$development_table <- function() .Call(wrap__CapeCodFit__development_table, self)

CapeCodFit$segment <- function(keys, values) .Call(wrap__CapeCodFit__segment, self, keys, values)

#' @export
`$.CapeCodFit` <- function (self, name) { func <- CapeCodFit[[name]]; environment(func) <- environment(); func }

#' @export
`[[.CapeCodFit` <- `$.CapeCodFit`

ClaimsDevelopmentResult <- new.env(parent = emptyenv())

ClaimsDevelopmentResult$origins <- function() .Call(wrap__ClaimsDevelopmentResult__origins, self)

ClaimsDevelopmentResult$one_year_standard_error <- function() .Call(wrap__ClaimsDevelopmentResult__one_year_standard_error, self)

ClaimsDevelopmentResult$total_one_year_standard_error <- function() .Call(wrap__ClaimsDevelopmentResult__total_one_year_standard_error, self)

ClaimsDevelopmentResult$by_calendar_year <- function() .Call(wrap__ClaimsDevelopmentResult__by_calendar_year, self)

ClaimsDevelopmentResult$total_by_calendar_year <- function() .Call(wrap__ClaimsDevelopmentResult__total_by_calendar_year, self)

ClaimsDevelopmentResult$run_off_standard_error <- function() .Call(wrap__ClaimsDevelopmentResult__run_off_standard_error, self)

ClaimsDevelopmentResult$total_run_off_standard_error <- function() .Call(wrap__ClaimsDevelopmentResult__total_run_off_standard_error, self)

#' @export
`$.ClaimsDevelopmentResult` <- function (self, name) { func <- ClaimsDevelopmentResult[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ClaimsDevelopmentResult` <- `$.ClaimsDevelopmentResult`

OdpBootstrapFit <- new.env(parent = emptyenv())

OdpBootstrapFit$chain_ladder <- function() .Call(wrap__OdpBootstrapFit__chain_ladder, self)

OdpBootstrapFit$fitted <- function() .Call(wrap__OdpBootstrapFit__fitted, self)

OdpBootstrapFit$residuals <- function() .Call(wrap__OdpBootstrapFit__residuals, self)

OdpBootstrapFit$scale <- function() .Call(wrap__OdpBootstrapFit__scale, self)

OdpBootstrapFit$reserves <- function() .Call(wrap__OdpBootstrapFit__reserves, self)

OdpBootstrapFit$long_table <- function() .Call(wrap__OdpBootstrapFit__long_table, self)

OdpBootstrapFit$totals_table <- function() .Call(wrap__OdpBootstrapFit__totals_table, self)

OdpBootstrapFit$development_table <- function() .Call(wrap__OdpBootstrapFit__development_table, self)

OdpBootstrapFit$segment <- function(keys, values) .Call(wrap__OdpBootstrapFit__segment, self, keys, values)

#' @export
`$.OdpBootstrapFit` <- function (self, name) { func <- OdpBootstrapFit[[name]]; environment(func) <- environment(); func }

#' @export
`[[.OdpBootstrapFit` <- `$.OdpBootstrapFit`

MackBootstrapFit <- new.env(parent = emptyenv())

MackBootstrapFit$chain_ladder <- function() .Call(wrap__MackBootstrapFit__chain_ladder, self)

MackBootstrapFit$mack <- function() .Call(wrap__MackBootstrapFit__mack, self)

MackBootstrapFit$residuals <- function() .Call(wrap__MackBootstrapFit__residuals, self)

MackBootstrapFit$reserves <- function() .Call(wrap__MackBootstrapFit__reserves, self)

MackBootstrapFit$long_table <- function() .Call(wrap__MackBootstrapFit__long_table, self)

MackBootstrapFit$totals_table <- function() .Call(wrap__MackBootstrapFit__totals_table, self)

MackBootstrapFit$development_table <- function() .Call(wrap__MackBootstrapFit__development_table, self)

MackBootstrapFit$segment <- function(keys, values) .Call(wrap__MackBootstrapFit__segment, self, keys, values)

#' @export
`$.MackBootstrapFit` <- function (self, name) { func <- MackBootstrapFit[[name]]; environment(func) <- environment(); func }

#' @export
`[[.MackBootstrapFit` <- `$.MackBootstrapFit`

OneYearFit <- new.env(parent = emptyenv())

OneYearFit$model <- function() .Call(wrap__OneYearFit__model, self)

OneYearFit$chain_ladder <- function() .Call(wrap__OneYearFit__chain_ladder, self)

OneYearFit$mack <- function() .Call(wrap__OneYearFit__mack, self)

OneYearFit$opening_ultimate <- function() .Call(wrap__OneYearFit__opening_ultimate, self)

OneYearFit$opening_reserve <- function() .Call(wrap__OneYearFit__opening_reserve, self)

OneYearFit$scale <- function() .Call(wrap__OneYearFit__scale, self)

OneYearFit$cdr <- function() .Call(wrap__OneYearFit__cdr, self)

OneYearFit$long_table <- function() .Call(wrap__OneYearFit__long_table, self)

OneYearFit$totals_table <- function() .Call(wrap__OneYearFit__totals_table, self)

OneYearFit$development_table <- function() .Call(wrap__OneYearFit__development_table, self)

OneYearFit$segment <- function(keys, values) .Call(wrap__OneYearFit__segment, self, keys, values)

#' @export
`$.OneYearFit` <- function (self, name) { func <- OneYearFit[[name]]; environment(func) <- environment(); func }

#' @export
`[[.OneYearFit` <- `$.OneYearFit`

ClarkFit <- new.env(parent = emptyenv())

ClarkFit$chain_ladder <- function() .Call(wrap__ClarkFit__chain_ladder, self)

ClarkFit$method <- function() .Call(wrap__ClarkFit__method, self)

ClarkFit$curve <- function() .Call(wrap__ClarkFit__curve, self)

ClarkFit$max_age <- function() .Call(wrap__ClarkFit__max_age, self)

ClarkFit$omega <- function() .Call(wrap__ClarkFit__omega, self)

ClarkFit$theta <- function() .Call(wrap__ClarkFit__theta, self)

ClarkFit$elr <- function() .Call(wrap__ClarkFit__elr, self)

ClarkFit$origin_width <- function() .Call(wrap__ClarkFit__origin_width, self)

ClarkFit$n_observations <- function() .Call(wrap__ClarkFit__n_observations, self)

ClarkFit$scale <- function() .Call(wrap__ClarkFit__scale, self)

ClarkFit$covariance <- function() .Call(wrap__ClarkFit__covariance, self)

ClarkFit$exposure <- function() .Call(wrap__ClarkFit__exposure, self)

ClarkFit$expected_ultimate <- function() .Call(wrap__ClarkFit__expected_ultimate, self)

ClarkFit$ultimate <- function() .Call(wrap__ClarkFit__ultimate, self)

ClarkFit$reserve <- function() .Call(wrap__ClarkFit__reserve, self)

ClarkFit$process_risk <- function() .Call(wrap__ClarkFit__process_risk, self)

ClarkFit$parameter_risk <- function() .Call(wrap__ClarkFit__parameter_risk, self)

ClarkFit$standard_error <- function() .Call(wrap__ClarkFit__standard_error, self)

ClarkFit$total_ultimate <- function() .Call(wrap__ClarkFit__total_ultimate, self)

ClarkFit$total_reserve <- function() .Call(wrap__ClarkFit__total_reserve, self)

ClarkFit$total_process_risk <- function() .Call(wrap__ClarkFit__total_process_risk, self)

ClarkFit$total_parameter_risk <- function() .Call(wrap__ClarkFit__total_parameter_risk, self)

ClarkFit$total_standard_error <- function() .Call(wrap__ClarkFit__total_standard_error, self)

ClarkFit$growth <- function(age) .Call(wrap__ClarkFit__growth, self, age)

ClarkFit$long_table <- function() .Call(wrap__ClarkFit__long_table, self)

ClarkFit$totals_table <- function() .Call(wrap__ClarkFit__totals_table, self)

ClarkFit$segment <- function(keys, values) .Call(wrap__ClarkFit__segment, self, keys, values)

#' @export
`$.ClarkFit` <- function (self, name) { func <- ClarkFit[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ClarkFit` <- `$.ClarkFit`

EvtTail <- new.env(parent = emptyenv())

EvtTail$fit <- function(draws, level) .Call(wrap__EvtTail__fit, draws, level)

EvtTail$threshold <- function() .Call(wrap__EvtTail__threshold, self)

EvtTail$p_exceed <- function() .Call(wrap__EvtTail__p_exceed, self)

EvtTail$xi <- function() .Call(wrap__EvtTail__xi, self)

EvtTail$beta <- function() .Call(wrap__EvtTail__beta, self)

EvtTail$var <- function(p) .Call(wrap__EvtTail__var, self, p)

EvtTail$tvar <- function(p) .Call(wrap__EvtTail__tvar, self, p)

#' @export
`$.EvtTail` <- function (self, name) { func <- EvtTail[[name]]; environment(func) <- environment(); func }

#' @export
`[[.EvtTail` <- `$.EvtTail`

RiskDistortion <- new.env(parent = emptyenv())

RiskDistortion$new <- function(kind, params, weights, r0) .Call(wrap__RiskDistortion__new, kind, params, weights, r0)

RiskDistortion$mixture <- function(parts, weights) .Call(wrap__RiskDistortion__mixture, parts, weights)

RiskDistortion$minimum <- function(parts) .Call(wrap__RiskDistortion__minimum, parts)

RiskDistortion$convex <- function(s, g) .Call(wrap__RiskDistortion__convex, s, g)

RiskDistortion$calibrate <- function(family, x, premium, assets, r0) .Call(wrap__RiskDistortion__calibrate, family, x, premium, assets, r0)

RiskDistortion$kind <- function() .Call(wrap__RiskDistortion__kind, self)

RiskDistortion$param <- function() .Call(wrap__RiskDistortion__param, self)

RiskDistortion$mass <- function() .Call(wrap__RiskDistortion__mass, self)

RiskDistortion$g_inv <- function(y) .Call(wrap__RiskDistortion__g_inv, self, y)

RiskDistortion$g_dual <- function(s) .Call(wrap__RiskDistortion__g_dual, self, s)

RiskDistortion$g <- function(s) .Call(wrap__RiskDistortion__g, self, s)

RiskDistortion$weights <- function(n) .Call(wrap__RiskDistortion__weights, self, n)

RiskDistortion$measure <- function(x) .Call(wrap__RiskDistortion__measure, self, x)

RiskDistortion$capital <- function(pd, method) .Call(wrap__RiskDistortion__capital, self, pd, method)

RiskDistortion$allocate <- function(pd) .Call(wrap__RiskDistortion__allocate, self, pd)

#' @export
`$.RiskDistortion` <- function (self, name) { func <- RiskDistortion[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RiskDistortion` <- `$.RiskDistortion`

RiskCopula <- new.env(parent = emptyenv())

RiskCopula$gaussian <- function(correlation, dim) .Call(wrap__RiskCopula__gaussian, correlation, dim)

RiskCopula$student_t <- function(correlation, dim, nu) .Call(wrap__RiskCopula__student_t, correlation, dim, nu)

RiskCopula$archimedean <- function(family, theta, dim) .Call(wrap__RiskCopula__archimedean, family, theta, dim)

RiskCopula$dim <- function() .Call(wrap__RiskCopula__dim, self)

RiskCopula$description <- function() .Call(wrap__RiskCopula__description, self)

RiskCopula$sample <- function(n, seed) .Call(wrap__RiskCopula__sample, self, n, seed)

RiskCopula$simulate <- function(marginals, n_sims, seed, dims, keys) .Call(wrap__RiskCopula__simulate, self, marginals, n_sims, seed, dims, keys)

#' @export
`$.RiskCopula` <- function (self, name) { func <- RiskCopula[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RiskCopula` <- `$.RiskCopula`
